// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: templates/lexer.jflex

import java_cup.runtime.SymbolFactory;
import java.io.StringReader;
import java.io.Reader;
import java.io.File;
import java.io.FileReader;
import jflex.base.Pair;
import java.util.Optional;
import java.util.Map;
import java.util.LinkedHashMap;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\41\u1f00\1\u0100\1\u3000\1\u3100\1\u0100"+
    "\1\u3200\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u1f00\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00"+
    "\1\u4f00\1\u5000\1\u1f00\3\u0100\1\u5100\1\u5200\1\u5300\12\u1f00"+
    "\4\u0100\1\u5400\17\u1f00\2\u0100\1\u5500\41\u1f00\2\u0100\1\u5600"+
    "\1\u5700\2\u1f00\1\u5800\1\u5900\27\u0100\1\u5a00\2\u0100\1\u5b00"+
    "\45\u1f00\1\u0100\1\u5c00\1\u5d00\11\u1f00\1\u5e00\24\u1f00\1\u5f00"+
    "\1\u6000\1\u1f00\1\u6100\1\u6200\1\u6300\1\u6400\2\u1f00\1\u6500"+
    "\5\u1f00\1\u6600\1\u6700\1\u6800\5\u1f00\1\u6900\1\u6a00\4\u1f00"+
    "\1\u6b00\2\u1f00\1\u6c00\16\u1f00\246\u0100\1\u6d00\20\u0100\1\u6e00"+
    "\1\u6f00\25\u0100\1\u7000\34\u0100\1\u7100\14\u1f00\2\u0100\1\u7200"+
    "\u0b06\u1f00\1\u7300\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\0"+
    "\1\6\1\7\1\10\11\0\1\11\1\12\12\13\2\0"+
    "\1\14\1\15\1\16\2\0\32\17\1\20\1\0\1\21"+
    "\1\0\1\22\1\0\1\23\3\17\1\24\1\25\1\17"+
    "\1\26\1\27\2\17\1\30\1\31\1\32\1\33\1\34"+
    "\1\17\1\35\1\36\1\37\1\40\5\17\12\0\1\3"+
    "\32\0\1\1\11\0\1\17\12\0\1\17\4\0\1\17"+
    "\5\0\27\17\1\0\37\17\1\0\u01ca\17\4\0\14\17"+
    "\16\0\5\17\7\0\1\17\1\0\1\17\21\0\160\22"+
    "\5\17\1\0\2\17\2\0\4\17\1\0\1\17\6\0"+
    "\1\17\1\0\3\17\1\0\1\17\1\0\24\17\1\0"+
    "\123\17\1\0\213\17\1\0\7\22\246\17\1\0\46\17"+
    "\2\0\1\17\6\0\51\17\10\0\55\22\1\0\1\22"+
    "\1\0\2\22\1\0\2\22\1\0\1\22\10\0\33\17"+
    "\4\0\4\17\35\0\13\22\5\0\53\17\25\22\12\13"+
    "\4\0\2\17\1\22\143\17\1\0\1\17\7\22\2\0"+
    "\6\22\2\17\2\22\1\0\4\22\2\17\12\13\3\17"+
    "\2\0\1\17\20\0\1\17\1\22\36\17\33\22\2\0"+
    "\131\17\13\22\1\17\16\0\12\13\41\17\11\22\2\17"+
    "\4\0\1\17\2\0\1\22\2\0\26\17\4\22\1\17"+
    "\11\22\1\17\3\22\1\17\5\22\22\0\31\17\3\22"+
    "\4\0\13\17\65\0\25\17\1\0\10\17\25\0\17\22"+
    "\1\0\41\22\66\17\3\22\1\17\22\22\1\17\7\22"+
    "\12\17\2\22\2\0\12\13\1\0\20\17\3\22\1\0"+
    "\10\17\2\0\2\17\2\0\26\17\1\0\7\17\1\0"+
    "\1\17\3\0\4\17\2\0\1\22\1\17\7\22\2\0"+
    "\2\22\2\0\3\22\1\17\10\0\1\22\4\0\2\17"+
    "\1\0\3\17\2\22\2\0\12\13\2\17\12\0\1\17"+
    "\1\0\1\22\2\0\3\22\1\0\6\17\4\0\2\17"+
    "\2\0\26\17\1\0\7\17\1\0\2\17\1\0\2\17"+
    "\1\0\2\17\2\0\1\22\1\0\5\22\4\0\2\22"+
    "\2\0\3\22\3\0\1\22\7\0\4\17\1\0\1\17"+
    "\7\0\12\13\2\22\3\17\1\22\13\0\3\22\1\0"+
    "\11\17\1\0\3\17\1\0\26\17\1\0\7\17\1\0"+
    "\2\17\1\0\5\17\2\0\1\22\1\17\10\22\1\0"+
    "\3\22\1\0\3\22\2\0\1\17\17\0\2\17\2\22"+
    "\2\0\12\13\11\0\1\17\6\22\1\0\3\22\1\0"+
    "\10\17\2\0\2\17\2\0\26\17\1\0\7\17\1\0"+
    "\2\17\1\0\5\17\2\0\1\22\1\17\7\22\2\0"+
    "\2\22\2\0\3\22\10\0\2\22\4\0\2\17\1\0"+
    "\3\17\2\22\2\0\12\13\1\0\1\17\20\0\1\22"+
    "\1\17\1\0\6\17\3\0\3\17\1\0\4\17\3\0"+
    "\2\17\1\0\1\17\1\0\2\17\3\0\2\17\3\0"+
    "\3\17\3\0\14\17\4\0\5\22\3\0\3\22\1\0"+
    "\4\22\2\0\1\17\6\0\1\22\16\0\12\13\20\0"+
    "\5\22\10\17\1\0\3\17\1\0\27\17\1\0\20\17"+
    "\3\0\1\17\7\22\1\0\3\22\1\0\4\22\7\0"+
    "\2\22\1\0\3\17\5\0\2\17\2\22\2\0\12\13"+
    "\20\0\1\17\3\22\1\0\10\17\1\0\3\17\1\0"+
    "\27\17\1\0\12\17\1\0\5\17\2\0\1\22\1\17"+
    "\7\22\1\0\3\22\1\0\4\22\7\0\2\22\7\0"+
    "\1\17\1\0\2\17\2\22\2\0\12\13\1\0\2\17"+
    "\15\0\4\22\1\0\10\17\1\0\3\17\1\0\51\17"+
    "\2\22\1\17\7\22\1\0\3\22\1\0\4\22\1\17"+
    "\5\0\3\17\1\22\7\0\3\17\2\22\2\0\12\13"+
    "\12\0\6\17\2\0\2\22\1\0\22\17\3\0\30\17"+
    "\1\0\11\17\1\0\1\17\2\0\7\17\3\0\1\22"+
    "\4\0\6\22\1\0\1\22\1\0\10\22\6\0\12\13"+
    "\2\0\2\22\15\0\60\17\1\22\2\17\7\22\5\0"+
    "\7\17\10\22\1\0\12\13\47\0\2\17\1\0\1\17"+
    "\1\0\5\17\1\0\30\17\1\0\1\17\1\0\12\17"+
    "\1\22\2\17\11\22\1\17\2\0\5\17\1\0\1\17"+
    "\1\0\6\22\2\0\12\13\2\0\4\17\40\0\1\17"+
    "\27\0\2\22\6\0\12\13\13\0\1\22\1\0\1\22"+
    "\1\0\1\22\4\0\2\22\10\17\1\0\44\17\4\0"+
    "\24\22\1\0\2\22\5\17\13\22\1\0\44\22\11\0"+
    "\1\22\71\0\53\17\24\22\1\17\12\13\6\0\6\17"+
    "\4\22\4\17\3\22\1\17\3\22\2\17\7\22\3\17"+
    "\4\22\15\17\14\22\1\17\1\22\12\13\4\22\2\0"+
    "\46\17\1\0\1\17\5\0\1\17\2\0\53\17\1\0"+
    "\115\17\1\0\4\17\2\0\7\17\1\0\1\17\1\0"+
    "\4\17\2\0\51\17\1\0\4\17\2\0\41\17\1\0"+
    "\4\17\2\0\7\17\1\0\1\17\1\0\4\17\2\0"+
    "\17\17\1\0\71\17\1\0\4\17\2\0\103\17\2\0"+
    "\3\22\40\0\20\17\20\0\126\17\2\0\6\17\3\0"+
    "\u016c\17\2\0\21\17\1\1\32\17\5\0\113\17\3\0"+
    "\3\22\10\17\7\0\15\17\1\0\4\17\3\22\13\0"+
    "\22\17\3\22\13\0\22\17\2\22\14\0\15\17\1\0"+
    "\3\17\1\0\2\22\14\0\64\17\40\22\3\0\1\17"+
    "\4\0\1\17\1\22\2\0\12\13\41\0\3\22\2\0"+
    "\12\13\6\0\131\17\7\0\5\17\2\22\42\17\1\22"+
    "\1\17\5\0\106\17\12\0\37\17\1\0\14\22\4\0"+
    "\14\22\12\0\12\13\36\17\2\0\5\17\13\0\54\17"+
    "\4\0\32\17\6\0\12\13\46\0\27\17\5\22\4\0"+
    "\65\17\12\22\1\0\35\22\2\0\1\22\12\13\6\0"+
    "\12\13\15\0\1\17\10\0\17\22\101\0\5\22\57\17"+
    "\21\22\7\17\4\0\12\13\21\0\11\22\14\0\3\22"+
    "\36\17\15\22\2\17\12\13\54\17\16\22\14\0\44\17"+
    "\24\22\10\0\12\13\3\0\3\17\12\13\44\17\2\0"+
    "\11\17\7\0\53\17\2\0\3\17\20\0\3\22\1\0"+
    "\25\22\4\17\1\22\6\17\1\22\2\17\3\22\1\17"+
    "\5\0\300\17\72\22\1\0\5\22\26\17\2\0\6\17"+
    "\2\0\46\17\2\0\6\17\2\0\10\17\1\0\1\17"+
    "\1\0\1\17\1\0\1\17\1\0\37\17\2\0\65\17"+
    "\1\0\7\17\1\0\1\17\3\0\3\17\1\0\7\17"+
    "\3\0\4\17\2\0\6\17\4\0\15\17\5\0\3\17"+
    "\1\0\7\17\3\0\13\1\35\0\2\3\5\0\1\1"+
    "\17\0\2\22\23\0\1\22\12\0\1\1\21\0\1\17"+
    "\15\0\1\17\20\0\15\17\63\0\41\22\21\0\1\17"+
    "\4\0\1\17\2\0\12\17\1\0\1\17\3\0\5\17"+
    "\6\0\1\17\1\0\1\17\1\0\1\17\1\0\4\17"+
    "\1\0\13\17\2\0\4\17\5\0\5\17\4\0\1\17"+
    "\21\0\43\22\2\17\4\22\u022d\0\64\22\26\0\57\17"+
    "\1\0\57\17\1\0\205\17\6\0\4\17\3\22\2\17"+
    "\14\0\46\17\1\0\1\17\5\0\1\17\2\0\70\17"+
    "\7\0\1\17\17\0\1\22\27\17\11\0\7\17\1\0"+
    "\7\17\1\0\7\17\1\0\7\17\1\0\7\17\1\0"+
    "\7\17\1\0\7\17\1\0\7\17\1\0\40\22\57\0"+
    "\1\17\320\0\1\1\4\0\2\17\1\22\31\0\17\22"+
    "\1\0\5\17\2\0\3\22\2\17\4\0\126\17\2\0"+
    "\2\22\2\0\3\17\1\0\132\17\1\0\4\17\5\0"+
    "\53\17\1\0\136\17\21\0\33\17\65\0\306\17\112\0"+
    "\360\17\20\0\215\17\103\0\56\17\2\0\15\17\3\0"+
    "\20\17\12\13\2\17\24\0\57\17\4\22\1\0\12\22"+
    "\1\0\37\17\2\22\106\17\14\22\45\0\11\17\2\0"+
    "\147\17\2\0\65\17\2\0\5\17\60\0\13\17\1\22"+
    "\3\17\1\22\4\17\1\22\27\17\5\22\30\0\64\17"+
    "\14\0\2\22\62\17\22\22\12\0\12\13\6\0\22\22"+
    "\6\17\3\0\1\17\1\0\2\17\1\22\12\13\34\17"+
    "\10\22\2\0\27\17\15\22\14\0\35\17\3\0\4\22"+
    "\57\17\16\22\16\0\1\17\12\13\6\0\5\17\1\22"+
    "\12\17\12\13\5\17\1\0\51\17\16\22\11\0\3\17"+
    "\1\22\10\17\2\22\2\0\12\13\6\0\27\17\3\0"+
    "\1\17\3\22\62\17\1\22\1\17\3\22\2\17\2\22"+
    "\5\17\2\22\1\17\1\22\1\17\30\0\3\17\2\0"+
    "\13\17\5\22\2\0\3\17\2\22\12\0\6\17\2\0"+
    "\6\17\2\0\6\17\11\0\7\17\1\0\7\17\1\0"+
    "\53\17\1\0\14\17\10\0\163\17\10\22\1\0\2\22"+
    "\2\0\12\13\6\0\244\17\14\0\27\17\4\0\61\17"+
    "\4\0\156\17\2\0\152\17\46\0\7\17\14\0\5\17"+
    "\5\0\1\17\1\22\12\17\1\0\15\17\1\0\5\17"+
    "\1\0\1\17\1\0\2\17\1\0\2\17\1\0\154\17"+
    "\41\0\153\17\22\0\100\17\2\0\66\17\50\0\14\17"+
    "\4\0\20\22\20\0\20\22\3\0\2\22\30\0\3\22"+
    "\40\0\5\17\1\0\207\17\23\0\12\13\7\0\32\17"+
    "\4\0\1\22\1\0\32\17\13\0\131\17\3\0\6\17"+
    "\2\0\6\17\2\0\6\17\2\0\3\17\43\0\14\17"+
    "\1\0\32\17\1\0\23\17\1\0\2\17\1\0\17\17"+
    "\2\0\16\17\42\0\173\17\105\0\65\22\210\0\1\22"+
    "\202\0\35\17\3\0\61\17\17\0\1\22\37\0\40\17"+
    "\15\0\24\17\1\22\10\17\1\22\5\0\46\17\5\22"+
    "\5\0\36\17\2\0\44\17\4\0\10\17\1\0\5\22"+
    "\52\0\236\17\2\0\12\13\6\0\44\17\4\0\44\17"+
    "\4\0\50\17\10\0\64\17\234\0\67\17\11\0\26\17"+
    "\12\0\10\17\230\0\6\17\2\0\1\17\1\0\54\17"+
    "\1\0\2\17\3\0\1\17\2\0\27\17\12\0\27\17"+
    "\11\0\37\17\101\0\23\17\1\0\2\17\12\0\26\17"+
    "\12\0\32\17\106\0\70\17\6\0\2\17\100\0\1\17"+
    "\3\22\1\0\2\22\5\0\4\22\4\17\1\0\3\17"+
    "\1\0\35\17\2\0\3\22\4\0\1\22\40\0\35\17"+
    "\3\0\35\17\43\0\10\17\1\0\34\17\2\22\31\0"+
    "\66\17\12\0\26\17\12\0\23\17\15\0\22\17\156\0"+
    "\111\17\67\0\63\17\15\0\63\17\15\0\44\17\4\22"+
    "\10\0\12\13\306\0\35\17\12\0\1\17\10\0\26\17"+
    "\13\22\217\0\27\17\11\0\3\22\65\17\17\22\37\0"+
    "\12\13\17\0\4\22\55\17\13\22\25\0\31\17\7\0"+
    "\12\13\6\0\3\22\44\17\16\22\1\0\12\13\4\0"+
    "\1\17\2\22\11\0\43\17\1\22\2\0\1\17\11\0"+
    "\3\22\60\17\16\22\4\17\4\0\4\22\3\0\12\13"+
    "\1\17\1\0\1\17\43\0\22\17\1\0\31\17\14\22"+
    "\6\0\1\22\101\0\7\17\1\0\1\17\1\0\4\17"+
    "\1\0\17\17\1\0\12\17\7\0\57\17\14\22\5\0"+
    "\12\13\6\0\4\22\1\0\10\17\2\0\2\17\2\0"+
    "\26\17\1\0\7\17\1\0\2\17\1\0\5\17\1\0"+
    "\2\22\1\17\7\22\2\0\2\22\2\0\3\22\2\0"+
    "\1\17\6\0\1\22\5\0\5\17\2\22\2\0\7\22"+
    "\3\0\5\22\213\0\65\17\22\22\4\17\5\0\12\13"+
    "\4\0\1\22\1\17\40\0\60\17\24\22\2\17\1\0"+
    "\1\17\10\0\12\13\246\0\57\17\7\22\2\0\11\22"+
    "\27\0\4\17\2\22\42\0\60\17\21\22\3\0\1\17"+
    "\13\0\12\13\46\0\53\17\15\22\1\17\7\0\12\13"+
    "\66\0\33\17\2\0\17\22\4\0\12\13\306\0\54\17"+
    "\17\22\145\0\100\17\12\13\25\0\1\17\240\0\10\17"+
    "\2\0\47\17\7\22\2\0\7\22\1\17\1\0\1\17"+
    "\1\22\33\0\1\17\12\22\50\17\7\22\1\17\4\22"+
    "\10\0\1\22\10\0\1\17\13\22\56\17\20\22\3\0"+
    "\1\17\42\0\71\17\7\0\11\17\1\0\45\17\10\22"+
    "\1\0\10\22\1\17\17\0\12\13\30\0\36\17\2\0"+
    "\26\22\1\0\16\22\111\0\7\17\1\0\2\17\1\0"+
    "\46\17\6\22\3\0\1\22\1\0\2\22\1\0\7\22"+
    "\1\17\1\22\10\0\12\13\6\0\6\17\1\0\2\17"+
    "\1\0\40\17\5\22\1\0\2\22\1\0\5\22\1\17"+
    "\7\0\12\13\u0136\0\23\17\4\22\11\0\232\17\146\0"+
    "\157\22\21\0\304\17\274\0\57\17\321\0\107\17\271\0"+
    "\71\17\7\0\37\17\1\0\12\13\146\0\36\17\2\0"+
    "\5\22\13\0\60\17\7\22\11\0\4\17\14\0\12\13"+
    "\11\0\25\17\5\0\23\17\260\0\100\17\200\0\113\17"+
    "\4\0\1\22\1\17\67\22\7\0\4\22\15\17\100\0"+
    "\2\17\1\0\1\17\34\0\370\17\10\0\363\17\15\0"+
    "\37\17\61\0\3\17\21\0\4\17\10\0\u018c\17\4\0"+
    "\153\17\5\0\15\17\3\0\11\17\7\0\12\17\3\0"+
    "\2\22\306\0\5\22\3\0\6\22\10\0\10\22\2\0"+
    "\7\22\36\0\4\22\224\0\3\22\273\0\125\17\1\0"+
    "\107\17\1\0\2\17\2\0\1\17\2\0\2\17\2\0"+
    "\4\17\1\0\14\17\1\0\1\17\1\0\7\17\1\0"+
    "\101\17\1\0\4\17\2\0\10\17\1\0\7\17\1\0"+
    "\34\17\1\0\4\17\1\0\5\17\1\0\1\17\3\0"+
    "\7\17\1\0\u0154\17\2\0\31\17\1\0\31\17\1\0"+
    "\37\17\1\0\31\17\1\0\37\17\1\0\31\17\1\0"+
    "\37\17\1\0\31\17\1\0\37\17\1\0\31\17\1\0"+
    "\10\17\2\0\62\13\67\22\4\0\62\22\10\0\1\22"+
    "\16\0\1\22\26\0\5\22\1\0\17\22\120\0\7\22"+
    "\1\0\21\22\2\0\7\22\1\0\2\22\1\0\5\22"+
    "\325\0\55\17\3\0\7\22\7\17\2\0\12\13\4\0"+
    "\1\17\u0171\0\54\17\4\22\12\13\6\0\305\17\13\0"+
    "\7\22\51\0\104\17\7\22\1\17\4\0\12\13\246\0"+
    "\4\17\1\0\33\17\1\0\2\17\1\0\1\17\2\0"+
    "\1\17\1\0\12\17\1\0\4\17\1\0\1\17\1\0"+
    "\1\17\6\0\1\17\4\0\1\17\1\0\1\17\1\0"+
    "\1\17\1\0\3\17\1\0\2\17\1\0\1\17\2\0"+
    "\1\17\1\0\1\17\1\0\1\17\1\0\1\17\1\0"+
    "\1\17\1\0\2\17\1\0\1\17\2\0\4\17\1\0"+
    "\7\17\1\0\4\17\1\0\4\17\1\0\1\17\1\0"+
    "\12\17\1\0\21\17\5\0\3\17\1\0\5\17\1\0"+
    "\21\17\164\0\32\22\6\0\32\22\6\0\32\22\166\0"+
    "\327\17\51\0\65\17\13\0\336\17\2\0\u0182\17\16\0"+
    "\u0131\17\37\0\36\17\342\0\360\22\20\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29696];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\3\0\1\2\1\3\1\4\1\0\3\4"+
    "\1\5\2\6\1\7\1\0\4\4\1\0\1\10\4\4"+
    "\1\7\2\4\1\11\4\4\1\0\1\12\3\0\1\13";

  private static int [] zzUnpackAction() {
    int [] result = new int[41];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\41\0\306"+
    "\0\347\0\u0108\0\u0129\0\u014a\0\41\0\41\0\u016b\0\u018c"+
    "\0\u01ad\0\u01ce\0\u01ef\0\u0210\0\u0231\0\u0252\0\41\0\u0273"+
    "\0\u0294\0\u02b5\0\u02d6\0\u02f7\0\u0318\0\u0339\0\306\0\u035a"+
    "\0\u037b\0\u039c\0\u03bd\0\u03de\0\306\0\u03ff\0\u0420\0\u0441"+
    "\0\41";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[41];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\5\2\1\3\1\4\1\5\2\0\1\6\1\0"+
    "\1\7\1\0\1\10\1\11\2\0\2\10\1\12\1\10"+
    "\1\13\7\10\1\14\1\10\41\0\6\3\1\15\32\3"+
    "\2\4\2\16\1\17\34\4\17\0\1\20\3\0\16\20"+
    "\13\0\1\6\40\0\1\10\3\0\1\10\2\0\17\10"+
    "\17\0\1\21\3\0\16\21\13\0\1\10\3\0\1\10"+
    "\2\0\1\10\1\22\15\10\13\0\1\10\3\0\1\10"+
    "\2\0\7\10\1\23\1\24\6\10\13\0\1\10\3\0"+
    "\1\10\2\0\13\10\1\25\3\10\2\0\1\16\47\0"+
    "\1\26\1\0\1\20\3\0\1\20\2\0\17\20\13\0"+
    "\1\21\3\0\1\21\1\0\1\27\17\21\13\0\1\10"+
    "\3\0\1\10\2\0\6\10\1\30\10\10\13\0\1\10"+
    "\3\0\1\10\2\0\12\10\1\31\4\10\13\0\1\10"+
    "\3\0\1\10\2\0\4\10\1\32\12\10\13\0\1\10"+
    "\3\0\1\10\2\0\16\10\1\33\17\0\1\34\3\0"+
    "\16\34\13\0\1\10\3\0\1\10\2\0\14\10\1\33"+
    "\2\10\13\0\1\10\3\0\1\10\2\0\11\10\1\35"+
    "\5\10\13\0\1\10\3\0\1\10\2\0\2\10\1\36"+
    "\14\10\13\0\1\10\3\0\1\10\2\0\2\10\1\37"+
    "\14\10\13\0\1\34\3\0\1\34\2\0\17\34\13\0"+
    "\1\10\3\0\1\10\2\0\13\10\1\40\3\10\13\0"+
    "\1\10\3\0\1\10\2\0\13\10\1\41\3\10\13\0"+
    "\1\10\3\0\1\10\2\0\15\10\1\42\1\10\13\0"+
    "\1\10\3\0\1\10\2\0\5\10\1\43\11\10\5\0"+
    "\1\44\5\0\1\10\3\0\1\10\2\0\17\10\13\0"+
    "\1\10\3\0\1\10\2\0\15\10\1\45\1\10\14\0"+
    "\1\46\35\0\1\47\1\50\1\47\3\0\1\47\2\0"+
    "\17\47\11\0\1\47\1\50\1\47\2\0\1\51\1\47"+
    "\2\0\17\47\11\0\1\47\1\0\1\47\3\0\1\47"+
    "\2\0\17\47";

  private static int [] zzUnpacktrans() {
    int [] result = new int[1122];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\0\1\1\1\11\1\1\1\0\3\1"+
    "\2\11\2\1\1\0\4\1\1\0\1\11\14\1\1\0"+
    "\1\1\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[41];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** the stack of open (nested) input streams to read from */
  private java.util.Deque<ZzFlexStreamInfo> zzStreams
    = new java.util.ArrayDeque<ZzFlexStreamInfo>();

  /**
   * inner class used to store info for nested
   * input streams
   */
  private static final class ZzFlexStreamInfo {
    java.io.Reader zzReader;
    int zzEndRead;
    int zzStartRead;
    int zzCurrentPos;
    int zzMarkedPos;
    int yyline;
    long yychar;
    int yycolumn;
    char [] zzBuffer;
    boolean zzAtBOL;
    boolean zzAtEOF;
    boolean zzEOFDone;
    int zzFinalHighSurrogate;

    /** sets all values stored in this class */
    ZzFlexStreamInfo(java.io.Reader zzReader, int zzEndRead, int zzStartRead,
                  int zzCurrentPos, int zzMarkedPos, char [] zzBuffer,
                  boolean zzAtBOL, boolean zzAtEOF, boolean zzEOFDone,
                  int zzFinalHighSurrogate, int yyline, long yychar,
                  int yycolumn) {
      this.zzReader      = zzReader;
      this.zzEndRead     = zzEndRead;
      this.zzStartRead   = zzStartRead;
      this.zzCurrentPos  = zzCurrentPos;
      this.zzMarkedPos   = zzMarkedPos;
      this.zzBuffer      = zzBuffer;
      this.zzAtBOL       = zzAtBOL;
      this.zzAtEOF       = zzAtEOF;
      this.zzEOFDone     = zzEOFDone;
      this.zzFinalHighSurrogate = zzFinalHighSurrogate;
      this.yyline        = yyline;
      this.yychar        = yychar;
      this.yycolumn      = yycolumn;
    }
  }

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    SymbolFactory sf;
    Preprocessor preprocessor = new Preprocessor();

    public final AnnotatedComments annotatedComments = new AnnotatedComments();

    public Lexer(Reader input, SymbolFactory sf) {
        this(input);
        this.sf = sf;
    }

    public void parsedSection(String section){
         annotatedComments.parsedSection(section);
    }

    public void parsedAssignment(Assignment<?> assignment){
        annotatedComments.parsedAssignment(assignment);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;           // indicate end of file
    zzEndRead = zzStartRead;  // invalidate buffer

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Stores the current input stream on a stack, and
   * reads from a new stream. Lexical state, line,
   * char, and column counting remain untouched.
   *
   * The current input stream can be restored with
   * yypopStream (usually in an {@code <<EOF>>} action).
   *
   * @param reader the new input stream to read from
   *
   * @see #yypopStream()
   */
  public final void yypushStream(java.io.Reader reader) {
    zzStreams.push(
      new ZzFlexStreamInfo(zzReader, zzEndRead, zzStartRead, zzCurrentPos,
                        zzMarkedPos, zzBuffer, zzAtBOL, zzAtEOF, zzEOFDone,
                        zzFinalHighSurrogate, yyline, yychar, yycolumn)
    );
    zzBuffer = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];
    zzReader = reader;
    yyResetPosition();
  }


  /**
   * Closes the current input stream and continues to
   * read from the one on top of the stream stack.
   *
   * @throws java.util.NoSuchElementException
   *         if there is no further stream to read from.
   *
   * @throws java.io.IOException
   *         if there was an error in closing the stream.
   *
   * @see #yypushStream(java.io.Reader)
   */
  public final void yypopStream() throws java.io.IOException {
    zzReader.close();
    ZzFlexStreamInfo s = (ZzFlexStreamInfo) zzStreams.pop();
    zzBuffer      = s.zzBuffer;
    zzReader      = s.zzReader;
    zzEndRead     = s.zzEndRead;
    zzStartRead   = s.zzStartRead;
    zzCurrentPos  = s.zzCurrentPos;
    zzMarkedPos   = s.zzMarkedPos;
    zzAtBOL       = s.zzAtBOL;
    zzAtEOF       = s.zzAtEOF;
    zzEOFDone     = s.zzEOFDone;
    zzFinalHighSurrogate = s.zzFinalHighSurrogate;
    yyline        = s.yyline;
    yychar        = s.yychar;
    yycolumn      = s.yycolumn;
  }


  /**
   * Returns true iff there are still streams left
   * to read from on the stream stack.
   */
  public final boolean yymoreStreams() {
    return !zzStreams.isEmpty();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to {@code ZZ_INITIAL}.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream
   *
   * @see #yypushStream(java.io.Reader)
   * @see #yypopStream()
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }

  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      // cached fields:
      int zzCurrentPosL;
      int zzMarkedPosL = zzMarkedPos;
      int zzEndReadL = zzEndRead;
      char [] zzBufferL = zzBuffer;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                if(yymoreStreams()){
                            yypopStream();
                           }else{
                             return sf.newSymbol("EOF", ParserSym.EOF);
                           }
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignore */
            }
          // fall through
          case 12: break;
          case 2:
            { return sf.newSymbol("NUMBER", ParserSym.NUMBER, Integer.valueOf(yytext()));
            }
          // fall through
          case 13: break;
          case 3:
            { return sf.newSymbol("EQUAL", ParserSym.EQUAL, yytext());
            }
          // fall through
          case 14: break;
          case 4:
            { return sf.newSymbol("IDENTIFIER", ParserSym.IDENTIFIER, yytext());
            }
          // fall through
          case 15: break;
          case 5:
            { return sf.newSymbol("STRING", ParserSym.STRING, yytext());
            }
          // fall through
          case 16: break;
          case 6:
            { annotatedComments.push(yytext());
            }
          // fall through
          case 17: break;
          case 7:
            { final String[] t = yytext().substring(1).split("\\.", 2);
                           if(t.length == 2){
                               return sf.newSymbol("REFERENCE", ParserSym.REFERENCE, new Pair(Optional.of(t[0]), t[1]));
                           }
                           return sf.newSymbol("REFERENCE", ParserSym.REFERENCE, new Pair(Optional.empty(), t[0]));
            }
          // fall through
          case 18: break;
          case 8:
            { String s = yytext().substring(1,yylength()-1);
                            annotatedComments.lexedSection(s);
                            return sf.newSymbol("SECTION", ParserSym.SECTION, s);
            }
          // fall through
          case 19: break;
          case 9:
            { return sf.newSymbol("BOOL", ParserSym.BOOL, Boolean.valueOf(yytext()));
            }
          // fall through
          case 20: break;
          case 10:
            { return sf.newSymbol("INHERIT", ParserSym.INHERIT, yytext());
            }
          // fall through
          case 21: break;
          case 11:
            { // System.out.println(yytext().substring(8,yylength()-1));
                                Optional<FileReader> fileopt = preprocessor.process(yytext().substring(8,yylength()-1));
                                if (fileopt.isPresent()) {
                                    yypushStream(fileopt.get());
                                }
            }
          // fall through
          case 22: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
