
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int INHERIT = 4;
  public static final int BOOL = 9;
  public static final int NUMBER = 7;
  public static final int EQUAL = 5;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int SECTION = 3;
  public static final int REFERENCE = 6;
  public static final int error = 1;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "SECTION",
  "INHERIT",
  "EQUAL",
  "REFERENCE",
  "NUMBER",
  "STRING",
  "BOOL"
  };
}

