-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrG.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrG.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transC :: GrG.Abs.C -> Result
transC x = case x of
  GrG.Abs.Chain cs -> failure x
  GrG.Abs.Repeat i c -> failure x
  GrG.Abs.Leaf double -> failure x

transI :: GrG.Abs.I -> Result
transI x = case x of
  GrG.Abs.IntVal integer -> failure x
