-- File generated by the BNF Converter (bnfc 2.9.5).
{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}

-- | The abstract syntax of language Parser.
module AST where

import Data.String qualified
import Prelude (Bool, Char, Double, Integer, String)
import Prelude qualified as C (
    Eq,
    Foldable,
    Functor,
    Int,
    Maybe (..),
    Ord,
    Read,
    Show,
    Traversable,
 )

data Block a = Block Position a [Instruction a]
    deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

data Instruction a
    = Statement Position a (Statement a)
    | Declaration Position a (Declaration a)
    deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

data Declaration a
    = ConstantDecl Position a Ident (Expr a)
    | VariableDecl Position a Ident (Type a) (Expr a)
    | FunctionDecl Position a Ident [Parameter a] (Type a) (Block a)
    deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

data Parameter a = Param a Modality Ident (Type a)
    deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

data Modality = DefaultByValue | ModalityVal | ModalityRef
    deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type a
    = ErrorType String
    | BoolType
    | CharType
    | IntType
    | StringType
    | FloatType
    | VoidType
    | ArrayType (C.Maybe (Expr a)) (Type a)
    | Pointer (Type a)
    --    | ArrayType Position a (Expr a) (Type a)
    --    | UnsizedArrayType Position a (Type a)
    deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

data Statement a
    = NestedBlock Position a (Block a)
    | -- | FunCall Position a Ident [Expr a]
      Break Position a
    | Continue Position a
    | ReturnVoid Position a
    | ReturnExp Position a (Expr a)
    | While Position a (Expr a) (Block a)
    | IfThen Position a (Expr a) (Block a)
    | IfThenElse Position a (Expr a) (Block a) (Block a)
    | Assignment Position a (Expr a) AssignmentOp (Expr a)
    | Expression Position a (Expr a)
    deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

-- \| IncrDecr Position a UnaryOp (Expr a)
--  | IncDec Position a (IncDec a)

data AssignmentOp = BasicAssignment | AssignMul | AssignAdd | AssignDiv | AssignSub | AssignPow | AssignAnd | AssignOr
    deriving (C.Eq, C.Ord, C.Show, C.Read)

data ArithOp = Add | Sub | Mul | Mod | Pow | Div
    deriving (C.Show, C.Eq, C.Ord, C.Read)

data BoolOp = Or | And
    deriving (C.Show, C.Eq, C.Ord, C.Read)

data RelOp = NotEq | GreaterThanEq | GreaterThan | LessThanEq | LessThan | Eq
    deriving (C.Show, C.Eq, C.Ord, C.Read)

data BasicLiteral a
    = IntLiteral a Integer
    | CharLiteral a Char
    | StringLiteral a String
    | FloatLiteral a Double
    | BoolLiteral a Bool
    deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

data BinaryOp
    = ArithmeticOp ArithOp
    | RelationalOp RelOp
    | BooleanOp BoolOp
    deriving (C.Show, C.Eq, C.Ord, C.Read)

data UnaryOp
    = Not
    | Neg
    | Coertion
    | PreDecr
    | PreIncr
    | PostDecr
    | PostIncr
    deriving (C.Show, C.Eq, C.Ord, C.Read)

-- data IncDec a
--    = PreIncr a (Expr a)
--    | PreDecr a (Expr a)
--    | PostIncr a (Expr a)
--    | PostDecr a (Expr a)
--     deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

data Expr a
    = UnaryOp Position a UnaryOp (Expr a)
    | BinaryOp Position a BinaryOp (Expr a) (Expr a)
    | --    | IncDecExpr Position a (IncDec a)
      Ref Position a (Expr a)
    | Deref Position a (Expr a)
    | ArrayAcc Position a (Expr a) (Expr a) -- to be CHecked!!!
    | Id Position a Ident
    | FunctionCall Position a Ident [Expr a]
    | BasicLiteral Position a (BasicLiteral a)
    | ArrayLiteral Position a [Expr a]
    | RangedArray Position a (Expr a) (Expr a)
    deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

newtype Ident = Ident String
    deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.
type Position = C.Maybe (C.Int, C.Int)

pattern NoPosition :: Position
pattern NoPosition = C.Nothing

pattern Position :: C.Int -> C.Int -> Position
pattern Position line col = C.Just (line, col)

-- | Get the start position of something.
