-- File generated by the BNF Converter (bnfc 2.9.5).
{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}

-- | The abstract syntax of language Parser.
module AST where
import PrettyPrinter
import Data.String qualified

type ParserOutput = ()
data ConstantSolverOutput = ConstantSolverOutput
    { replacedFromConstant :: Maybe (Instruction ParserOutput),
      maxRecursion :: Bool,
      constantAlreadyDefined :: Maybe (Instruction ParserOutput)
    }
    deriving (Eq, Ord, Show, Read)

data TypeCheckerOutput = TypeCheckerOutput {t :: Type, lrv :: Maybe LeftRightValue, modality :: Maybe Modality}
    deriving (Eq, Ord, Show, Read)

-- lrv is used to give information about the fact wether we want to generate
--  the l-value or right-value of an expression.
-- Recall that for every expressions representing a binaryOP I need the R-VALUE!!!
-- modality is used to give information about the modality of every identifier.
-- Default: for identifiers not being formal parameters the modality is by-value!
-- do we permit the following case: f(ref &int i) ??????
-- that is a formal paratameter having pointer type and modality by ref!!!

data LeftRightValue = LeftValue | RightValue
    deriving (Eq, Ord, Show, Read)

data Type
    = ErrorFType String
    | VoidFType
    | BoolFType
    | CharFType
    | IntFType
    | StringFType
    | FloatFType
    | ArrayFType Int Type
    | PointerFType Type
    | FunctionFType [(Modality, Type)] Type
    deriving (Eq, Ord, Show, Read)

instance PrettyPrinter Type where
    pp(IntFType) = "int"
    pp(BoolFType) = "bool"
    pp(CharFType) = "char"
    pp(FloatFType) = "float"
    pp(PointerFType _) = "ref"
    pp(_) = ""


type Block a = [Instruction a]

data Instruction a
    = NestedBlock Position (Block a) a
    | ConstantDecl Position Ident (Expr a) a
    | VariableDecl Position Ident (DeclType a) (Expr a) a
    | FunctionDecl Position Ident [Parameter a] (DeclType a) (Block a) a
    | Break Position a
    | Continue Position a
    | ReturnVoid Position a
    | ReturnExp Position (Expr a) a
    | While Position (Expr a) (Block a) a
    | IfThen Position (Expr a) (Block a) a
    | IfThenElse Position (Expr a) (Block a) (Block a) a
    | Assignment Position (Expr a) AssignmentOp (Expr a) a
    | Expression Position (Expr a) a
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

data AssignmentOp = BasicAssignment | AssignMul | AssignAdd | AssignDiv | AssignSub | AssignPow | AssignAnd | AssignOr
    deriving (Eq, Ord, Show, Read)

data Expr a
    = UnaryOp Position UnaryOp (Expr a) a
    | BinaryOp Position BinaryOp (Expr a) (Expr a) a
    | Ref Position (Expr a) a
    | Deref Position (Expr a) a
    | ArrayAcc Position (Expr a) (Expr a) a
    | Id Position Ident a
    | FunctionCall Position Ident [Expr a] a
    | BasicLiteral Position (BasicLiteral a) a
    | ArrayLiteral Position [Expr a] a
    | RangedArray Position (Expr a) (Expr a) a
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

data DeclType a
    = BoolType
    | CharType
    | IntType
    | StringType
    | FloatType
    | VoidType
    | ArrayType (Maybe (Expr a)) (DeclType a)
    | PointerType (DeclType a)
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

data Parameter a = Param Modality Ident (DeclType a) a
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

data Modality = ModalityVal | ModalityRef
    deriving (Eq, Ord, Show, Read)

data UnaryOp
    = Not
    | Neg
    | Coertion
    | PreDecr
    | PreIncr
    | PostDecr
    | PostIncr
    deriving (Show, Eq, Ord, Read)

instance PrettyPrinter UnaryOp where
    pp (Not) = "!"
    pp (Neg) = "-"
    pp (Coercion) = "()"
    pp (PreDecr) = "--"
    pp (PreIncr) = "++"
    pp (PostDecr) = "--"
    pp (PostIncr) = "++"

data BinaryOp
    = ArithmeticOp ArithOp
    | RelationalOp RelOp
    | BooleanOp BoolOp
    deriving (Show, Eq, Ord, Read)

instance PrettyPrinter BinaryOp where
    pp (ArithmeticOp ar) = pp ar
    pp (RelationalOp rel) = pp rel
    pp (BooleanOp bol) = pp bol


data ArithOp = Add | Sub | Mul | Mod | Pow | Div
    deriving (Show, Eq, Ord, Read)

instance PrettyPrinter ArithOp where
    pp (Add) = "+"
    pp (Sub) = "-"
    pp (Mul) = "*"
    pp (Mod) = "%"   
    pp (Pow) = "^"
    pp (Div) = "/"

data RelOp = NotEq | GreaterThanEq | GreaterThan | LessThanEq | LessThan | Eq
    deriving (Show, Eq, Ord, Read)

instance PrettyPrinter RelOp where
    pp (NotEq) = "!="
    pp (GreaterThanEq) = ">="
    pp (GreaterThan) = ">"
    pp (LessThanEq) = "<="   
    pp (LessThan) = "<"
    pp (Eq) = "=="

data BoolOp = Or | And
    deriving (Show, Eq, Ord, Read)

instance PrettyPrinter BoolOp where
    pp (Or) = "||"
    pp (And) = "&&"

newtype Ident = Ident String
    deriving (Eq, Ord, Show, Read, Data.String.IsString)

data BasicLiteral a
    = IntLiteral Integer a
    | CharLiteral Char a
    | StringLiteral String a
    | FloatLiteral Double a
    | BoolLiteral Bool a
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

-- | Start position (line, column) of something.
type Position = Maybe (Int, Int)

pattern NoPosition :: Position
pattern NoPosition = Nothing

-- | Get the start position of something.
pattern Position :: Int -> Int -> Position
pattern Position line col = Just (line, col)
