-- File generated by the BNF Converter (bnfc 2.9.5).
{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}

-- | The abstract syntax of language Parser.
module AST2 where

import Data.Map.Strict qualified as Map
import Data.String qualified

data ASTData
    = Parse ()
    | ResolveConstants {replacedFromConstant :: Maybe (Instruction ())}
    deriving (Eq, Ord, Show, Read)

--  | TypeChecker {t::, errors::[String]}

data Type
    = ErrorFType String
    | VoidFType
    | BoolFType
    | CharFType
    | IntFType
    | StringFType
    | FloatFType
    | ArrayFType Int Type
    | PointerFType Type
    | FunctionFType [(Modality, Type)] Type

data DeclType a
    = BoolType
    | CharType
    | IntType
    | StringType
    | FloatType
    | VoidType
    | ArrayType (Maybe (Expr a)) (DeclType a)
    | PointerType (DeclType a)
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

type Block a = [Instruction a]

data Instruction a
    = NestedBlock Position (Block a) a
    | -- \| NestedBlock (Block a) a
      ConstantDecl Position Ident (Expr a) a
    | VariableDecl Position Ident (DeclType a) (Expr a) a
    | FunctionDecl Position Ident [Parameter a] (DeclType a) (Block a) a
    | Break Position a
    | Continue Position a
    | ReturnVoid Position a
    | ReturnExp Position (Expr a) a
    | While Position (Expr a) (Block a) a
    | IfThen Position (Expr a) (Block a) a
    | IfThenElse Position (Expr a) (Block a) (Block a) a
    | Assignment Position (Expr a) AssignmentOp (Expr a) a
    | Expression Position (Expr a) a
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

data Parameter a = Param Modality Ident (DeclType a) a
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

data Modality = ModalityVal | ModalityRef
    deriving (Eq, Ord, Show, Read)

data Expr a
    = UnaryOp Position UnaryOp (Expr a) a
    | BinaryOp Position BinaryOp (Expr a) (Expr a) a
    | Ref Position (Expr a) a
    | Deref Position (Expr a) a
    | ArrayAcc Position (Expr a) (Expr a) a
    | Id Position Ident a
    | FunctionCall Position Ident [Expr a] a
    | BasicLiteral Position (BasicLiteral a) a
    | ArrayLiteral Position [Expr a] a
    | RangedArray Position (Expr a) (Expr a) a
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

newtype Ident = Ident String
    deriving (Eq, Ord, Show, Read, Data.String.IsString)

data AssignmentOp = BasicAssignment | AssignMul | AssignAdd | AssignDiv | AssignSub | AssignPow | AssignAnd | AssignOr
    deriving (Eq, Ord, Show, Read)

data ArithOp = Add | Sub | Mul | Mod | Pow | Div
    deriving (Show, Eq, Ord, Read)

data BoolOp = Or | And
    deriving (Show, Eq, Ord, Read)

data RelOp = NotEq | GreaterThanEq | GreaterThan | LessThanEq | LessThan | Eq
    deriving (Show, Eq, Ord, Read)

data BasicLiteral a
    = IntLiteral Integer a
    | CharLiteral Char a
    | StringLiteral String a
    | FloatLiteral Double a
    | BoolLiteral Bool a
    deriving (Eq, Ord, Show, Read, Functor, Foldable, Traversable)

data BinaryOp
    = ArithmeticOp ArithOp
    | RelationalOp RelOp
    | BooleanOp BoolOp
    deriving (Show, Eq, Ord, Read)

data UnaryOp
    = Not
    | Neg
    | Coertion
    | PreDecr
    | PreIncr
    | PostDecr
    | PostIncr
    deriving (Show, Eq, Ord, Read)

-- | Start position (line, column) of something.
type Position = Maybe (Int, Int)

pattern NoPosition :: Position
pattern NoPosition = Nothing

-- | Get the start position of something.
pattern Position :: Int -> Int -> Position
pattern Position line col = Just (line, col)
