-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelDouble where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsDouble

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transE :: AbsDouble.E -> Result
transE x = case x of
  AbsDouble.Chain e es -> failure x
  AbsDouble.Repeat1 i e -> failure x
  AbsDouble.Repeat2 e i -> failure x
  AbsDouble.Leaf double -> failure x

transI :: AbsDouble.I -> Result
transI x = case x of
  AbsDouble.IntVal integer -> failure x
