;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname 1.7.1) (read-case-sensitive #t) (teachpacks ((lib "drawings.ss" "installed-teachpacks"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "drawings.ss" "installed-teachpacks")) #f)))
(define btr-val
  (lambda (btr)
    (let ((l (string-length btr)))
      (let ((lsd (string-ref btr (- l 1)))
            (pre (substring btr 0 (- l 1)))
            )
        (if (= l 1)
            (btd-val lsd)
            (+ (* 3 (btr-val pre))
               (btd-val lsd))
            ) 
        ))
    ))

(define btd-val
  (lambda (b)
    (cond ((char=? b #\-) -1)
          ((char=? b #\.) 0)
          (else 1)
          )
    ))

(btr-val ".")
(btr-val "+")
(btr-val "+-")
(btr-val "+.")
(btr-val "++")
(btr-val "+--")
(btr-val "+-.")
(btr-val "+-+")
(btr-val "+.-")
(btr-val "+..")
(btr-val "+.+")
(btr-val ".")
(btr-val "-")
(btr-val "-+")
(btr-val "-.")
(btr-val "--")
(btr-val "-++")
(btr-val "-+.")
(btr-val "-+-")
(btr-val "-.+")
(btr-val "-..")
(btr-val "-.-")