-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrD.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrD.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transC :: GrD.Abs.C -> Result
transC x = case x of
  GrD.Abs.Chain c1 c2 -> failure x
  GrD.Abs.Repeat i c -> failure x
  GrD.Abs.Leaf double -> failure x

transI :: GrD.Abs.I -> Result
transI x = case x of
  GrD.Abs.IntVal integer -> failure x
