-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrB.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrB.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transC :: GrB.Abs.C -> Result
transC x = case x of
  GrB.Abs.Chain cs -> failure x
  GrB.Abs.Repeat i c -> failure x
  GrB.Abs.Leaf double -> failure x

transI :: GrB.Abs.I -> Result
transI x = case x of
  GrB.Abs.IntVal integer -> failure x
