-- File generated by the BNF Converter (bnfc 2.9.5).

-- | The abstract syntax of language prova.

module Abs where

data Tree a b = Leaf b | Chain [ Tree a b ] | Repeat a ( Tree a b )
  deriving (Show)