-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module Par
  ( happyError
  , myLexer
  , pE
  , pS
  ) where

import Prelude

import Abs
import Prova.Lex

}

%name pE E
%name pS S
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('      { PT _ (TS _ 1) }
  ')'      { PT _ (TS _ 2) }
  '*'      { PT _ (TS _ 3) }
  '+'      { PT _ (TS _ 4) }
  L_doubl  { PT _ (TD $$)  }
  L_integ  { PT _ (TI $$)  }
  L_quoted { PT _ (TL $$)  }

%%

E :: { Tree Int Double }
E : E1 { $1 } | E2 { $1 }

E1 :: { Tree Int Double }
E1 : E2 '+' ListE2 { Chain ($1 : $3) }

ListE2 :: { [Tree Int Double] }
ListE2 : E2 { (:[]) $1 } | E2 '+' ListE2 { (:) $1 $3 }

E2 :: { Tree Int Double }
E2 : E3 { $1 } | I '*' E4 { Repeat $1 $3 }

E4 :: { Tree Int Double }
E4 : '(' E1 ')' { $2 } | E3 { $1 }

E3 :: { Tree Int Double }
E3 : Double { Leaf $1 }

Double  :: { Double }
Double   : L_doubl  { $1 }

-------------

I :: { Int }
I : Integer { $1 }
Integer :: { Int }
Integer  : L_integ  { $1 }

-------------

S :: { Tree Int String }
S : S1 { $1 } | S2 { $1 }

S1 :: { Tree Int String }
S1 : S2 '+' ListS2 { Chain ($1 : $3) }

ListS2 :: { [Tree Int String] }
ListS2 : S2 { (:[]) $1 } | S2 '+' ListS2 { (:) $1 $3 }

S2 :: { Tree Int String }
S2 : S3 { $1 } | I '*' S4 { Repeat $1 $3 }

S4 :: { Tree Int String }
S4 : '(' S1 ')' { $2 } | S3 { $1 }

S3 :: { Tree Int String }
S3 : String { Leaf $1 }

String  :: { String }
String   : L_quoted  { $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

