-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Prova.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Prova.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transE :: Prova.Abs.E -> Result
transE x = case x of
  Prova.Abs.Chain e es -> failure x
  Prova.Abs.Repeat i e -> failure x
  Prova.Abs.Leaf double -> failure x

transS :: Prova.Abs.S -> Result
transS x = case x of
  Prova.Abs.Chain1 s ss -> failure x
  Prova.Abs.Repeat1 i s -> failure x
  Prova.Abs.Leaf1 string -> failure x

transI :: Prova.Abs.I -> Result
transI x = case x of
  Prova.Abs.IntVal1 integer -> failure x
