-- File generated by the BNF Converter (bnfc 2.9.5).

-- | The abstract syntax of language grJ.

module GrJ.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)

data E = Chain E [E] | Repeat I E | Leaf String
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data I = IntVal Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

