-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrJ.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrJ.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transE :: GrJ.Abs.E -> Result
transE x = case x of
  GrJ.Abs.Chain e es -> failure x
  GrJ.Abs.Repeat i e -> failure x
  GrJ.Abs.Leaf string -> failure x

transI :: GrJ.Abs.I -> Result
transI x = case x of
  GrJ.Abs.IntVal integer -> failure x
