-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Parser.

module Parser.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Parser.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Parser.Abs.Ident where
  prt _ (Parser.Abs.Ident i) = doc $ showString i
instance Print Parser.Abs.SBlock where
  prt i = \case
    Parser.Abs.Block instructions -> prPrec i 1 (concatD [prt 0 instructions])

instance Print Parser.Abs.Instruction where
  prt i = \case
    Parser.Abs.Statement sstatement -> prPrec i 0 (concatD [prt 0 sstatement])
    Parser.Abs.Declaration sdeclaration -> prPrec i 0 (concatD [prt 0 sdeclaration])

instance Print [Parser.Abs.Instruction] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Parser.Abs.SDeclaration where
  prt i = \case
    Parser.Abs.ConstDecl id_ type_ expr -> prPrec i 0 (concatD [doc (showString "def"), prt 0 id_, doc (showString ":"), prt 0 type_, doc (showString ":="), prt 0 expr])
    Parser.Abs.VarDecl id_ type_ expr -> prPrec i 0 (concatD [doc (showString "var"), prt 0 id_, doc (showString ":"), prt 0 type_, doc (showString ":="), prt 0 expr])
    Parser.Abs.FunDecl id_ parameters type_ sblock -> prPrec i 0 (concatD [doc (showString "def"), prt 0 id_, doc (showString "("), prt 0 parameters, doc (showString ")"), doc (showString ":"), prt 0 type_, prt 0 sblock])

instance Print [Parser.Abs.Parameter] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Parser.Abs.Parameter where
  prt i = \case
    Parser.Abs.Param modality id_ type_ -> prPrec i 0 (concatD [prt 0 modality, prt 0 id_, doc (showString ":"), prt 0 type_])

instance Print Parser.Abs.Modality where
  prt i = \case
    Parser.Abs.Modality1 -> prPrec i 0 (concatD [])
    Parser.Abs.Modality_val -> prPrec i 0 (concatD [doc (showString "val")])
    Parser.Abs.Modality_ref -> prPrec i 0 (concatD [doc (showString "ref")])

instance Print Parser.Abs.Type where
  prt i = \case
    Parser.Abs.BasicType sbasictype -> prPrec i 0 (concatD [prt 0 sbasictype])
    Parser.Abs.ArrayType expr type_ -> prPrec i 0 (concatD [doc (showString "["), prt 0 expr, doc (showString "]"), prt 0 type_])
    Parser.Abs.UnsizedArrayType type_ -> prPrec i 0 (concatD [doc (showString "["), doc (showString "]"), prt 0 type_])
    Parser.Abs.Pointer type_ -> prPrec i 0 (concatD [doc (showString "&"), prt 0 type_])

instance Print Parser.Abs.SBasicType where
  prt i = \case
    Parser.Abs.SBasicType_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    Parser.Abs.SBasicType_char -> prPrec i 0 (concatD [doc (showString "char")])
    Parser.Abs.SBasicType_int -> prPrec i 0 (concatD [doc (showString "int")])
    Parser.Abs.SBasicType_string -> prPrec i 0 (concatD [doc (showString "string")])
    Parser.Abs.SBasicType_float -> prPrec i 0 (concatD [doc (showString "float")])
    Parser.Abs.SBasicType_void -> prPrec i 0 (concatD [doc (showString "void")])

instance Print Parser.Abs.SStatement where
  prt i = \case
    Parser.Abs.Compound sblock -> prPrec i 0 (concatD [prt 0 sblock])
    Parser.Abs.ProcCall funcall -> prPrec i 0 (concatD [prt 0 funcall])
    Parser.Abs.Jump jumpsstatement -> prPrec i 0 (concatD [prt 0 jumpsstatement])
    Parser.Abs.Iter itersstatement -> prPrec i 0 (concatD [prt 0 itersstatement])
    Parser.Abs.Branch branchsstatement -> prPrec i 0 (concatD [prt 0 branchsstatement])
    Parser.Abs.Assign expr1 assignmentop expr2 -> prPrec i 0 (concatD [prt 0 expr1, prt 0 assignmentop, prt 0 expr2])
    Parser.Abs.PreInc expr -> prPrec i 1 (concatD [doc (showString "++"), prt 8 expr])
    Parser.Abs.PreDecr expr -> prPrec i 1 (concatD [doc (showString "--"), prt 8 expr])
    Parser.Abs.PostInc expr -> prPrec i 1 (concatD [prt 8 expr, doc (showString "++")])
    Parser.Abs.PostDecr expr -> prPrec i 1 (concatD [prt 8 expr, doc (showString "--")])

instance Print Parser.Abs.Assignment_op where
  prt i = \case
    Parser.Abs.AssignOp -> prPrec i 0 (concatD [doc (showString ":=")])
    Parser.Abs.AssignMul -> prPrec i 0 (concatD [doc (showString "*=")])
    Parser.Abs.AssignAdd -> prPrec i 0 (concatD [doc (showString "+=")])
    Parser.Abs.AssignDiv -> prPrec i 0 (concatD [doc (showString "/=")])
    Parser.Abs.AssignSub -> prPrec i 0 (concatD [doc (showString "-=")])
    Parser.Abs.AssignPow -> prPrec i 0 (concatD [doc (showString "^=")])
    Parser.Abs.AssignAnd -> prPrec i 0 (concatD [doc (showString "&=")])
    Parser.Abs.AssignOr -> prPrec i 0 (concatD [doc (showString "|=")])

instance Print Parser.Abs.JumpSStatement where
  prt i = \case
    Parser.Abs.Break -> prPrec i 0 (concatD [doc (showString "break")])
    Parser.Abs.Continue -> prPrec i 0 (concatD [doc (showString "continue")])
    Parser.Abs.RetExpVoid -> prPrec i 0 (concatD [doc (showString "return")])
    Parser.Abs.RetExp expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr])

instance Print Parser.Abs.BranchSStatement where
  prt i = \case
    Parser.Abs.IfNoElse expr sblock -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 sblock])
    Parser.Abs.IfElse expr sblock1 sblock2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 sblock1, doc (showString "else"), prt 0 sblock2])

instance Print Parser.Abs.IterSStatement where
  prt i = \case
    Parser.Abs.While expr sblock -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 sblock])

instance Print Parser.Abs.Expr where
  prt i = \case
    Parser.Abs.Or expr1 expr2 -> prPrec i 0 (concatD [prt 0 expr1, doc (showString "||"), prt 1 expr2])
    Parser.Abs.And expr1 expr2 -> prPrec i 1 (concatD [prt 1 expr1, doc (showString "&&"), prt 2 expr2])
    Parser.Abs.Not expr -> prPrec i 2 (concatD [doc (showString "!"), prt 3 expr])
    Parser.Abs.Eq expr1 expr2 -> prPrec i 3 (concatD [prt 4 expr1, doc (showString "=="), prt 4 expr2])
    Parser.Abs.Neq expr1 expr2 -> prPrec i 3 (concatD [prt 4 expr1, doc (showString "!="), prt 4 expr2])
    Parser.Abs.Lt expr1 expr2 -> prPrec i 3 (concatD [prt 4 expr1, doc (showString "<"), prt 4 expr2])
    Parser.Abs.LtE expr1 expr2 -> prPrec i 3 (concatD [prt 4 expr1, doc (showString "<="), prt 4 expr2])
    Parser.Abs.Gt expr1 expr2 -> prPrec i 3 (concatD [prt 4 expr1, doc (showString ">"), prt 4 expr2])
    Parser.Abs.GtE expr1 expr2 -> prPrec i 3 (concatD [prt 4 expr1, doc (showString ">="), prt 4 expr2])
    Parser.Abs.Add expr1 expr2 -> prPrec i 4 (concatD [prt 4 expr1, doc (showString "+"), prt 5 expr2])
    Parser.Abs.Sub expr1 expr2 -> prPrec i 4 (concatD [prt 4 expr1, doc (showString "-"), prt 5 expr2])
    Parser.Abs.Mul expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString "*"), prt 6 expr2])
    Parser.Abs.Div expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString "/"), prt 6 expr2])
    Parser.Abs.Mod expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString "%"), prt 6 expr2])
    Parser.Abs.Pow expr1 expr2 -> prPrec i 6 (concatD [prt 7 expr1, doc (showString "**"), prt 6 expr2])
    Parser.Abs.Neg expr -> prPrec i 7 (concatD [doc (showString "-"), prt 8 expr])
    Parser.Abs.Ref expr -> prPrec i 8 (concatD [doc (showString "&"), prt 8 expr])
    Parser.Abs.Deref expr -> prPrec i 8 (concatD [doc (showString "$"), prt 8 expr])
    Parser.Abs.ArrayAcc expr1 expr2 -> prPrec i 8 (concatD [prt 8 expr1, doc (showString "["), prt 0 expr2, doc (showString "]")])
    Parser.Abs.Id id_ -> prPrec i 9 (concatD [prt 0 id_])
    Parser.Abs.ExpAssign sstatement -> prPrec i 9 (concatD [prt 1 sstatement])
    Parser.Abs.FCall funcall -> prPrec i 10 (concatD [prt 0 funcall])
    Parser.Abs.Int n -> prPrec i 11 (concatD [prt 0 n])
    Parser.Abs.Char c -> prPrec i 11 (concatD [prt 0 c])
    Parser.Abs.String str -> prPrec i 11 (concatD [printString str])
    Parser.Abs.Float d -> prPrec i 11 (concatD [prt 0 d])
    Parser.Abs.Bool boolean -> prPrec i 11 (concatD [prt 0 boolean])
    Parser.Abs.Array exprs -> prPrec i 12 (concatD [doc (showString "["), prt 11 exprs, doc (showString "]")])

instance Print Parser.Abs.Boolean where
  prt i = \case
    Parser.Abs.Boolean_True -> prPrec i 0 (concatD [doc (showString "True")])
    Parser.Abs.Boolean_False -> prPrec i 0 (concatD [doc (showString "False")])

instance Print [Parser.Abs.Expr] where
  prt 11 [x] = concatD [prt 11 x]
  prt 11 (x:xs) = concatD [prt 11 x, doc (showString ","), prt 11 xs]
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Parser.Abs.FunCall where
  prt i = \case
    Parser.Abs.Call id_ exprs -> prPrec i 0 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
