-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Parser.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Parser.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Parser.Abs.Ident -> Result
transIdent x = case x of
  Parser.Abs.Ident string -> failure x

transBlock :: Show a => Parser.Abs.Block' a -> Result
transBlock x = case x of
  Parser.Abs.Blck _ instructions -> failure x

transInstruction :: Show a => Parser.Abs.Instruction' a -> Result
transInstruction x = case x of
  Parser.Abs.Stmt _ statement -> failure x
  Parser.Abs.Decl _ declaration -> failure x

transDeclaration :: Show a => Parser.Abs.Declaration' a -> Result
transDeclaration x = case x of
  Parser.Abs.ConstDecl _ ident expr -> failure x
  Parser.Abs.VarDecl _ ident type_ expr -> failure x
  Parser.Abs.FunDecl _ ident parameters type_ block -> failure x

transParameter :: Show a => Parser.Abs.Parameter' a -> Result
transParameter x = case x of
  Parser.Abs.Param _ modality ident type_ -> failure x

transModality :: Show a => Parser.Abs.Modality' a -> Result
transModality x = case x of
  Parser.Abs.Modality1 _ -> failure x
  Parser.Abs.Modality_val _ -> failure x
  Parser.Abs.Modality_ref _ -> failure x
  Parser.Abs.Modality_valres _ -> failure x
  Parser.Abs.Modality_res _ -> failure x

transType :: Show a => Parser.Abs.Type' a -> Result
transType x = case x of
  Parser.Abs.BsType _ basictype -> failure x
  Parser.Abs.ArrayType _ expr type_ -> failure x
  Parser.Abs.CArrType _ expr type_ -> failure x
  Parser.Abs.UnsizedArrayType _ type_ -> failure x
  Parser.Abs.UnsizedCArrayType _ type_ -> failure x
  Parser.Abs.Pointer _ type_ -> failure x

transBasicType :: Show a => Parser.Abs.BasicType' a -> Result
transBasicType x = case x of
  Parser.Abs.BasicType_bool _ -> failure x
  Parser.Abs.BasicType_char _ -> failure x
  Parser.Abs.BasicType_int _ -> failure x
  Parser.Abs.BasicType_string _ -> failure x
  Parser.Abs.BasicType_float _ -> failure x
  Parser.Abs.BasicType_void _ -> failure x

transStatement :: Show a => Parser.Abs.Statement' a -> Result
transStatement x = case x of
  Parser.Abs.Compound _ block -> failure x
  Parser.Abs.Jump _ jumpstatement -> failure x
  Parser.Abs.Iter _ iterstatement -> failure x
  Parser.Abs.Branch _ branchstatement -> failure x
  Parser.Abs.Assign _ expr1 assignmentop expr2 -> failure x
  Parser.Abs.TryStmt _ block1 block2 -> failure x
  Parser.Abs.Throw _ string -> failure x
  Parser.Abs.StmntExpr _ expr -> failure x

transAssignment_op :: Show a => Parser.Abs.Assignment_op' a -> Result
transAssignment_op x = case x of
  Parser.Abs.AssignOp _ -> failure x
  Parser.Abs.AssignMul _ -> failure x
  Parser.Abs.AssignAdd _ -> failure x
  Parser.Abs.AssignDiv _ -> failure x
  Parser.Abs.AssignSub _ -> failure x
  Parser.Abs.AssignPow _ -> failure x
  Parser.Abs.AssignAnd _ -> failure x
  Parser.Abs.AssignOr _ -> failure x

transJumpStatement :: Show a => Parser.Abs.JumpStatement' a -> Result
transJumpStatement x = case x of
  Parser.Abs.Break _ -> failure x
  Parser.Abs.Continue _ -> failure x
  Parser.Abs.RetExpVoid _ -> failure x
  Parser.Abs.RetExp _ expr -> failure x

transBranchStatement :: Show a => Parser.Abs.BranchStatement' a -> Result
transBranchStatement x = case x of
  Parser.Abs.If _ expr block -> failure x
  Parser.Abs.IfElse _ expr block1 block2 -> failure x

transIterStatement :: Show a => Parser.Abs.IterStatement' a -> Result
transIterStatement x = case x of
  Parser.Abs.While _ expr block -> failure x
  Parser.Abs.DoWhile _ block expr -> failure x
  Parser.Abs.For _ ident expr1 expr2 expr3 block -> failure x

transExpr :: Show a => Parser.Abs.Expr' a -> Result
transExpr x = case x of
  Parser.Abs.IfExpr _ expr1 expr2 expr3 -> failure x
  Parser.Abs.Or _ expr1 expr2 -> failure x
  Parser.Abs.And _ expr1 expr2 -> failure x
  Parser.Abs.Not _ expr -> failure x
  Parser.Abs.Eq _ expr1 expr2 -> failure x
  Parser.Abs.Neq _ expr1 expr2 -> failure x
  Parser.Abs.Lt _ expr1 expr2 -> failure x
  Parser.Abs.LtE _ expr1 expr2 -> failure x
  Parser.Abs.Gt _ expr1 expr2 -> failure x
  Parser.Abs.GtE _ expr1 expr2 -> failure x
  Parser.Abs.Add _ expr1 expr2 -> failure x
  Parser.Abs.Sub _ expr1 expr2 -> failure x
  Parser.Abs.Mul _ expr1 expr2 -> failure x
  Parser.Abs.Div _ expr1 expr2 -> failure x
  Parser.Abs.Mod _ expr1 expr2 -> failure x
  Parser.Abs.Pow _ expr1 expr2 -> failure x
  Parser.Abs.Neg _ expr -> failure x
  Parser.Abs.PreInc _ expr -> failure x
  Parser.Abs.PreDecr _ expr -> failure x
  Parser.Abs.PostInc _ expr -> failure x
  Parser.Abs.PostDecr _ expr -> failure x
  Parser.Abs.Ref _ expr -> failure x
  Parser.Abs.Deref _ expr -> failure x
  Parser.Abs.ArrayAcc _ expr1 expr2 -> failure x
  Parser.Abs.Id _ ident -> failure x
  Parser.Abs.FunCall _ ident exprs -> failure x
  Parser.Abs.Int _ integer -> failure x
  Parser.Abs.Char _ char -> failure x
  Parser.Abs.String _ string -> failure x
  Parser.Abs.Float _ double -> failure x
  Parser.Abs.Bool _ boolean -> failure x
  Parser.Abs.Array _ exprs -> failure x

transBoolean :: Show a => Parser.Abs.Boolean' a -> Result
transBoolean x = case x of
  Parser.Abs.Boolean_True _ -> failure x
  Parser.Abs.Boolean_False _ -> failure x
