-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Parser.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Parser.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Parser.Abs.Ident -> Result
transIdent x = case x of
  Parser.Abs.Ident string -> failure x

transSBlock :: Parser.Abs.SBlock -> Result
transSBlock x = case x of
  Parser.Abs.Block instructions -> failure x

transInstruction :: Parser.Abs.Instruction -> Result
transInstruction x = case x of
  Parser.Abs.Statement sstatement -> failure x
  Parser.Abs.Declaration sdeclaration -> failure x

transSDeclaration :: Parser.Abs.SDeclaration -> Result
transSDeclaration x = case x of
  Parser.Abs.ConstDecl ident type_ expr -> failure x
  Parser.Abs.VarDecl ident type_ expr -> failure x
  Parser.Abs.FunDecl ident parameters type_ sblock -> failure x

transParameter :: Parser.Abs.Parameter -> Result
transParameter x = case x of
  Parser.Abs.Param modality ident type_ -> failure x

transModality :: Parser.Abs.Modality -> Result
transModality x = case x of
  Parser.Abs.Modality1 -> failure x
  Parser.Abs.Modality_val -> failure x
  Parser.Abs.Modality_ref -> failure x

transType :: Parser.Abs.Type -> Result
transType x = case x of
  Parser.Abs.BasicType sbasictype -> failure x
  Parser.Abs.ArrayType expr type_ -> failure x
  Parser.Abs.UnsizedArrayType type_ -> failure x
  Parser.Abs.Pointer type_ -> failure x

transSBasicType :: Parser.Abs.SBasicType -> Result
transSBasicType x = case x of
  Parser.Abs.SBasicType_bool -> failure x
  Parser.Abs.SBasicType_char -> failure x
  Parser.Abs.SBasicType_int -> failure x
  Parser.Abs.SBasicType_string -> failure x
  Parser.Abs.SBasicType_float -> failure x
  Parser.Abs.SBasicType_void -> failure x

transSStatement :: Parser.Abs.SStatement -> Result
transSStatement x = case x of
  Parser.Abs.Compound sblock -> failure x
  Parser.Abs.ProcCall funcall -> failure x
  Parser.Abs.Jump jumpsstatement -> failure x
  Parser.Abs.Iter itersstatement -> failure x
  Parser.Abs.Branch branchsstatement -> failure x
  Parser.Abs.Assign expr1 assignmentop expr2 -> failure x
  Parser.Abs.PreInc expr -> failure x
  Parser.Abs.PreDecr expr -> failure x
  Parser.Abs.PostInc expr -> failure x
  Parser.Abs.PostDecr expr -> failure x

transAssignment_op :: Parser.Abs.Assignment_op -> Result
transAssignment_op x = case x of
  Parser.Abs.AssignOp -> failure x
  Parser.Abs.AssignMul -> failure x
  Parser.Abs.AssignAdd -> failure x
  Parser.Abs.AssignDiv -> failure x
  Parser.Abs.AssignSub -> failure x
  Parser.Abs.AssignPow -> failure x
  Parser.Abs.AssignAnd -> failure x
  Parser.Abs.AssignOr -> failure x

transJumpSStatement :: Parser.Abs.JumpSStatement -> Result
transJumpSStatement x = case x of
  Parser.Abs.Break -> failure x
  Parser.Abs.Continue -> failure x
  Parser.Abs.RetExpVoid -> failure x
  Parser.Abs.RetExp expr -> failure x

transBranchSStatement :: Parser.Abs.BranchSStatement -> Result
transBranchSStatement x = case x of
  Parser.Abs.IfNoElse expr sblock -> failure x
  Parser.Abs.IfElse expr sblock1 sblock2 -> failure x

transIterSStatement :: Parser.Abs.IterSStatement -> Result
transIterSStatement x = case x of
  Parser.Abs.While expr sblock -> failure x

transExpr :: Parser.Abs.Expr -> Result
transExpr x = case x of
  Parser.Abs.Or expr1 expr2 -> failure x
  Parser.Abs.And expr1 expr2 -> failure x
  Parser.Abs.Not expr -> failure x
  Parser.Abs.Eq expr1 expr2 -> failure x
  Parser.Abs.Neq expr1 expr2 -> failure x
  Parser.Abs.Lt expr1 expr2 -> failure x
  Parser.Abs.LtE expr1 expr2 -> failure x
  Parser.Abs.Gt expr1 expr2 -> failure x
  Parser.Abs.GtE expr1 expr2 -> failure x
  Parser.Abs.Add expr1 expr2 -> failure x
  Parser.Abs.Sub expr1 expr2 -> failure x
  Parser.Abs.Mul expr1 expr2 -> failure x
  Parser.Abs.Div expr1 expr2 -> failure x
  Parser.Abs.Mod expr1 expr2 -> failure x
  Parser.Abs.Pow expr1 expr2 -> failure x
  Parser.Abs.Neg expr -> failure x
  Parser.Abs.Ref expr -> failure x
  Parser.Abs.Deref expr -> failure x
  Parser.Abs.ArrayAcc expr1 expr2 -> failure x
  Parser.Abs.Id ident -> failure x
  Parser.Abs.ExpAssign sstatement -> failure x
  Parser.Abs.FCall funcall -> failure x
  Parser.Abs.Int integer -> failure x
  Parser.Abs.Char char -> failure x
  Parser.Abs.String string -> failure x
  Parser.Abs.Float double -> failure x
  Parser.Abs.Bool boolean -> failure x
  Parser.Abs.Array exprs -> failure x

transBoolean :: Parser.Abs.Boolean -> Result
transBoolean x = case x of
  Parser.Abs.Boolean_True -> failure x
  Parser.Abs.Boolean_False -> failure x

transFunCall :: Parser.Abs.FunCall -> Result
transFunCall x = case x of
  Parser.Abs.Call ident exprs -> failure x
