-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelGrammar where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsGrammar

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsGrammar.Ident -> Result
transIdent x = case x of
  AbsGrammar.Ident string -> failure x

transSBlock :: AbsGrammar.SBlock -> Result
transSBlock x = case x of
  AbsGrammar.Block instructions -> failure x

transInstruction :: AbsGrammar.Instruction -> Result
transInstruction x = case x of
  AbsGrammar.Statement sstatement -> failure x
  AbsGrammar.Declaration sdeclaration -> failure x

transSDeclaration :: AbsGrammar.SDeclaration -> Result
transSDeclaration x = case x of
  AbsGrammar.ConstDecl ident type_ expr -> failure x
  AbsGrammar.VarDecl ident type_ expr -> failure x
  AbsGrammar.FunDecl ident parameters type_ sblock -> failure x

transParameter :: AbsGrammar.Parameter -> Result
transParameter x = case x of
  AbsGrammar.Param modality ident type_ -> failure x

transModality :: AbsGrammar.Modality -> Result
transModality x = case x of
  AbsGrammar.Modality1 -> failure x
  AbsGrammar.Modality_val -> failure x
  AbsGrammar.Modality_ref -> failure x

transType :: AbsGrammar.Type -> Result
transType x = case x of
  AbsGrammar.BasicType sbasictype -> failure x
  AbsGrammar.ArrayType expr type_ -> failure x
  AbsGrammar.UnsizedArrayType type_ -> failure x
  AbsGrammar.Pointer type_ -> failure x

transSBasicType :: AbsGrammar.SBasicType -> Result
transSBasicType x = case x of
  AbsGrammar.SBasicType_bool -> failure x
  AbsGrammar.SBasicType_char -> failure x
  AbsGrammar.SBasicType_int -> failure x
  AbsGrammar.SBasicType_string -> failure x
  AbsGrammar.SBasicType_float -> failure x
  AbsGrammar.SBasicType_void -> failure x

transSStatement :: AbsGrammar.SStatement -> Result
transSStatement x = case x of
  AbsGrammar.Compound sblock -> failure x
  AbsGrammar.ProcCall funcall -> failure x
  AbsGrammar.Jump jumpsstatement -> failure x
  AbsGrammar.Iter itersstatement -> failure x
  AbsGrammar.Branch branchsstatement -> failure x
  AbsGrammar.Assign expr1 assignmentop expr2 -> failure x
  AbsGrammar.PreInc expr -> failure x
  AbsGrammar.PreDecr expr -> failure x
  AbsGrammar.PostInc expr -> failure x
  AbsGrammar.PostDecr expr -> failure x

transAssignment_op :: AbsGrammar.Assignment_op -> Result
transAssignment_op x = case x of
  AbsGrammar.AssignOp -> failure x
  AbsGrammar.AssignMul -> failure x
  AbsGrammar.AssignAdd -> failure x
  AbsGrammar.AssignDiv -> failure x
  AbsGrammar.AssignSub -> failure x
  AbsGrammar.AssignPow -> failure x
  AbsGrammar.AssignAnd -> failure x
  AbsGrammar.AssignOr -> failure x

transJumpSStatement :: AbsGrammar.JumpSStatement -> Result
transJumpSStatement x = case x of
  AbsGrammar.Break -> failure x
  AbsGrammar.Continue -> failure x
  AbsGrammar.RetExpVoid -> failure x
  AbsGrammar.RetExp expr -> failure x

transBranchSStatement :: AbsGrammar.BranchSStatement -> Result
transBranchSStatement x = case x of
  AbsGrammar.IfNoElse expr sblock -> failure x
  AbsGrammar.IfElse expr sblock1 sblock2 -> failure x

transIterSStatement :: AbsGrammar.IterSStatement -> Result
transIterSStatement x = case x of
  AbsGrammar.While expr sblock -> failure x

transExpr :: AbsGrammar.Expr -> Result
transExpr x = case x of
  AbsGrammar.Or expr1 expr2 -> failure x
  AbsGrammar.And expr1 expr2 -> failure x
  AbsGrammar.Not expr -> failure x
  AbsGrammar.Eq expr1 expr2 -> failure x
  AbsGrammar.Neq expr1 expr2 -> failure x
  AbsGrammar.Lt expr1 expr2 -> failure x
  AbsGrammar.LtE expr1 expr2 -> failure x
  AbsGrammar.Gt expr1 expr2 -> failure x
  AbsGrammar.GtE expr1 expr2 -> failure x
  AbsGrammar.Add expr1 expr2 -> failure x
  AbsGrammar.Sub expr1 expr2 -> failure x
  AbsGrammar.Mul expr1 expr2 -> failure x
  AbsGrammar.Div expr1 expr2 -> failure x
  AbsGrammar.Mod expr1 expr2 -> failure x
  AbsGrammar.Pow expr1 expr2 -> failure x
  AbsGrammar.Neg expr -> failure x
  AbsGrammar.ExpAssign sstatement -> failure x
  AbsGrammar.Ref expr -> failure x
  AbsGrammar.Deref expr -> failure x
  AbsGrammar.ArrayAcc expr1 expr2 -> failure x
  AbsGrammar.Id ident -> failure x
  AbsGrammar.FCall funcall -> failure x
  AbsGrammar.Int integer -> failure x
  AbsGrammar.Char char -> failure x
  AbsGrammar.String string -> failure x
  AbsGrammar.Float double -> failure x
  AbsGrammar.Bool boolean -> failure x
  AbsGrammar.Array exprs -> failure x
  AbsGrammar.RangedArray expr1 expr2 -> failure x

transBoolean :: AbsGrammar.Boolean -> Result
transBoolean x = case x of
  AbsGrammar.Boolean_True -> failure x
  AbsGrammar.Boolean_False -> failure x

transFunCall :: AbsGrammar.FunCall -> Result
transFunCall x = case x of
  AbsGrammar.Call ident exprs -> failure x
