-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module GrC.Par
  ( happyError
  , myLexer
  , pC
  , pC1
  , pC2
  , pI
  , pC3
  ) where

import Prelude

import qualified GrC.Abs
import GrC.Lex

}

%name pC C
%name pC1 C1
%name pC2 C2
%name pI I
%name pC3 C3
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '*'      { PT _ (TS _ 1) }
  '+'      { PT _ (TS _ 2) }
  L_doubl  { PT _ (TD $$)  }
  L_integ  { PT _ (TI $$)  }

%%

Double  :: { Double }
Double   : L_doubl  { (read $1) :: Double }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

C :: { GrC.Abs.C }
C : C '+' C1 { GrC.Abs.Sum $1 $3 } | C1 { $1 }

C1 :: { GrC.Abs.C }
C1 : I '*' C2 { GrC.Abs.Repeat $1 $3 } | C3 { $1 }

C2 :: { GrC.Abs.C }
C2 : C { $1 }

I :: { GrC.Abs.I }
I : Integer { GrC.Abs.IntVal $1 }

C3 :: { GrC.Abs.C }
C3 : Double { GrC.Abs.Leaf $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

