-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrC.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrC.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transC :: GrC.Abs.C -> Result
transC x = case x of
  GrC.Abs.Sum c1 c2 -> failure x
  GrC.Abs.Repeat i c -> failure x
  GrC.Abs.Leaf double -> failure x

transI :: GrC.Abs.I -> Result
transI x = case x of
  GrC.Abs.IntVal integer -> failure x
