-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module GrE.Par
  ( happyError
  , myLexer
  , pE
  , pE1
  , pE2
  , pListE3
  , pE3
  , pE4
  , pI
  ) where

import Prelude

import qualified GrE.Abs
import GrE.Lex

}

%name pE E
%name pE1 E1
%name pE2 E2
%name pListE3 ListE3
%name pE3 E3
%name pE4 E4
%name pI I
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('      { PT _ (TS _ 1) }
  ')'      { PT _ (TS _ 2) }
  '*'      { PT _ (TS _ 3) }
  '+'      { PT _ (TS _ 4) }
  L_doubl  { PT _ (TD $$)  }
  L_integ  { PT _ (TI $$)  }

%%

Double  :: { Double }
Double   : L_doubl  { (read $1) :: Double }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

E :: { GrE.Abs.E }
E : E1 { $1 } | E2 { $1 } | E3 { $1 }

E1 :: { GrE.Abs.E }
E1 : '(' E2 ')' { $2 } | Double { GrE.Abs.Leaf $1 }

E2 :: { GrE.Abs.E }
E2 : E3 '+' ListE3 { GrE.Abs.Chain $1 $3 }

ListE3 :: { [GrE.Abs.E] }
ListE3 : E3 { (:[]) $1 } | E3 '+' ListE3 { (:) $1 $3 }

E3 :: { GrE.Abs.E }
E3
  : I '*' E1 { GrE.Abs.Repeat $1 $3 }
  | E4 { $1 }
  | I '*' E4 { GrE.Abs.Repeat $1 $3 }

E4 :: { GrE.Abs.E }
E4 : Double { GrE.Abs.Leaf $1 }

I :: { GrE.Abs.I }
I : Integer { GrE.Abs.IntVal $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

