-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrE.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrE.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transE :: GrE.Abs.E -> Result
transE x = case x of
  GrE.Abs.Chain e es -> failure x
  GrE.Abs.Repeat i e -> failure x
  GrE.Abs.Leaf double -> failure x

transI :: GrE.Abs.I -> Result
transI x = case x of
  GrE.Abs.IntVal integer -> failure x
