-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language grammatica.

module Grammatica.Abs where

import Prelude (Char, Double, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data SBlock = Block [Instruction]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Instruction = Statement SStatement | Declaration SDeclaration
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SDeclaration
    = ConstDecl Ident Type Expr
    | VarDecl Ident Type Expr
    | FunDecl Ident [Parameter] Type SBlock
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Parameter = Param Modality Ident Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Modality = Modality1 | Modality_val | Modality_ref
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type
    = BasicType SBasicType
    | ArrayType Expr Type
    | UnsizedArrayType Type
    | Pointer Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SBasicType
    = SBasicType_bool
    | SBasicType_char
    | SBasicType_int
    | SBasicType_string
    | SBasicType_float
    | SBasicType_void
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SStatement
    = Compound SBlock
    | ProcCall FunCall
    | Jump JumpSStatement
    | Iter IterSStatement
    | Branch BranchSStatement
    | Assign Expr Assignment_op Expr
    | PreInc Expr
    | PreDecr Expr
    | PostInc Expr
    | PostDecr Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Assignment_op
    = AssignOp
    | AssignMul
    | AssignAdd
    | AssignDiv
    | AssignSub
    | AssignPow
    | AssignAnd
    | AssignOr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data JumpSStatement = Break | Continue | RetExpVoid | RetExp Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BranchSStatement
    = IfNoElse Expr SBlock | IfElse Expr SBlock SBlock
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data IterSStatement = While Expr SBlock
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr
    = Or Expr Expr
    | And Expr Expr
    | Not Expr
    | Eq Expr Expr
    | Neq Expr Expr
    | Lt Expr Expr
    | LtE Expr Expr
    | Gt Expr Expr
    | GtE Expr Expr
    | Add Expr Expr
    | Sub Expr Expr
    | Mul Expr Expr
    | Div Expr Expr
    | Mod Expr Expr
    | Pow Expr Expr
    | Neg Expr
    | Ref Expr
    | Deref Expr
    | ArrayAcc Expr Expr
    | Id Ident
    | ExpAssign SStatement
    | FCall FunCall
    | Int Integer
    | Char Char
    | String String
    | Float Double
    | Bool Boolean
    | Array [Expr]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Boolean = Boolean_True | Boolean_False
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FunCall = Call Ident [Expr]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

