-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language grammatica.

module Grammatica.Abs where

import Prelude (Char, Double, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = Prog [Decl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decl
    = ConstDecl Ident Type RExpr
    | VarDecl Ident Type RExpr
    | FunDecl Ident [Parameter] Type Block
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Parameter = Param Ident Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type = BasType BasicType | CompType CompoundType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BasicType
    = BasicType_bool
    | BasicType_char
    | BasicType_int
    | BasicType_string
    | BasicType_float
    | BasicType_void
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Boolean = Boolean_True | Boolean_False
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data CompoundType
    = ArrDef RExpr Type | ArrPartialDef Type | Pointer Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Block = BlockDecl [Decl] [Statement]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Statement
    = Comp Block
    | Jmp JumpStatement
    | Iter IterStatement
    | Sel SelectionStatement
    | Assgn LExpr Assignment_op RExpr
    | LExprStatement LExpr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Assignment_op
    = Assign
    | AssgnMul
    | AssgnAdd
    | AssgnDiv
    | AssgnSub
    | AssgnPow
    | AssgnAnd
    | AssgnOr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data JumpStatement = Break | Continue | RetExpVoid | RetExp RExpr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SelectionStatement
    = IfNoElse RExpr Block | IfElse RExpr Block Block
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data IterStatement = While RExpr Block
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RExpr
    = Or RExpr RExpr
    | And RExpr RExpr
    | Not RExpr
    | Eq RExpr RExpr
    | Neq RExpr RExpr
    | Lt RExpr RExpr
    | LtE RExpr RExpr
    | Gt RExpr RExpr
    | GtE RExpr RExpr
    | Add RExpr RExpr
    | Sub RExpr RExpr
    | Mul RExpr RExpr
    | Div RExpr RExpr
    | Mod RExpr RExpr
    | Pow RExpr RExpr
    | Neg RExpr
    | Ref LExpr
    | Int Integer
    | Char Char
    | String String
    | Float Double
    | Bool Boolean
    | Array [RExpr]
    | Lexpr LExpr
    | Increment Incr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Incr
    = PreInc BLExpr | PreDecr BLExpr | PostInc BLExpr | PostDecr BLExpr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LExpr = Deref RExpr | BasLExpr BLExpr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BLExpr = ArrayEl BLExpr RExpr | Id Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

