-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module Grammatica.Par
  ( happyError
  , myLexer
  , pSBlock1
  ) where

import Prelude

import qualified Grammatica.Abs
import Grammatica.Lex

}

%name pSBlock1 SBlock1
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '!'        { PT _ (TS _ 1)  }
  '!='       { PT _ (TS _ 2)  }
  '$'        { PT _ (TS _ 3)  }
  '%'        { PT _ (TS _ 4)  }
  '&'        { PT _ (TS _ 5)  }
  '&&'       { PT _ (TS _ 6)  }
  '&='       { PT _ (TS _ 7)  }
  '('        { PT _ (TS _ 8)  }
  ')'        { PT _ (TS _ 9)  }
  '*'        { PT _ (TS _ 10) }
  '**'       { PT _ (TS _ 11) }
  '*='       { PT _ (TS _ 12) }
  '+'        { PT _ (TS _ 13) }
  '++'       { PT _ (TS _ 14) }
  '+='       { PT _ (TS _ 15) }
  ','        { PT _ (TS _ 16) }
  '-'        { PT _ (TS _ 17) }
  '--'       { PT _ (TS _ 18) }
  '-='       { PT _ (TS _ 19) }
  '/'        { PT _ (TS _ 20) }
  '/='       { PT _ (TS _ 21) }
  ':'        { PT _ (TS _ 22) }
  ':='       { PT _ (TS _ 23) }
  ';'        { PT _ (TS _ 24) }
  '<'        { PT _ (TS _ 25) }
  '<='       { PT _ (TS _ 26) }
  '=='       { PT _ (TS _ 27) }
  '>'        { PT _ (TS _ 28) }
  '>='       { PT _ (TS _ 29) }
  'False'    { PT _ (TS _ 30) }
  'True'     { PT _ (TS _ 31) }
  '['        { PT _ (TS _ 32) }
  ']'        { PT _ (TS _ 33) }
  '^='       { PT _ (TS _ 34) }
  'bool'     { PT _ (TS _ 35) }
  'break'    { PT _ (TS _ 36) }
  'char'     { PT _ (TS _ 37) }
  'continue' { PT _ (TS _ 38) }
  'def'      { PT _ (TS _ 39) }
  'else'     { PT _ (TS _ 40) }
  'float'    { PT _ (TS _ 41) }
  'if'       { PT _ (TS _ 42) }
  'int'      { PT _ (TS _ 43) }
  'ref'      { PT _ (TS _ 44) }
  'return'   { PT _ (TS _ 45) }
  'string'   { PT _ (TS _ 46) }
  'val'      { PT _ (TS _ 47) }
  'var'      { PT _ (TS _ 48) }
  'void'     { PT _ (TS _ 49) }
  'while'    { PT _ (TS _ 50) }
  '{'        { PT _ (TS _ 51) }
  '|='       { PT _ (TS _ 52) }
  '||'       { PT _ (TS _ 53) }
  '}'        { PT _ (TS _ 54) }
  L_Ident    { PT _ (TV $$)   }
  L_charac   { PT _ (TC $$)   }
  L_doubl    { PT _ (TD $$)   }
  L_integ    { PT _ (TI $$)   }
  L_quoted   { PT _ (TL $$)   }

%%

Ident :: { Grammatica.Abs.Ident }
Ident  : L_Ident { Grammatica.Abs.Ident $1 }

Char    :: { Char }
Char     : L_charac { (read $1) :: Char }

Double  :: { Double }
Double   : L_doubl  { (read $1) :: Double }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

String  :: { String }
String   : L_quoted { $1 }

SBlock :: { Grammatica.Abs.SBlock }
SBlock : '{' SBlock1 '}' { $2 }

SBlock1 :: { Grammatica.Abs.SBlock }
SBlock1 : ListInstruction { Grammatica.Abs.Block $1 }

Instruction :: { Grammatica.Abs.Instruction }
Instruction
  : SStatement { Grammatica.Abs.Statement $1 }
  | SDeclaration { Grammatica.Abs.Declaration $1 }

ListInstruction :: { [Grammatica.Abs.Instruction] }
ListInstruction
  : {- empty -} { [] }
  | Instruction { (:[]) $1 }
  | Instruction ';' ListInstruction { (:) $1 $3 }

SDeclaration :: { Grammatica.Abs.SDeclaration }
SDeclaration
  : 'def' Ident ':' Type ':=' Expr { Grammatica.Abs.ConstDecl $2 $4 $6 }
  | 'var' Ident ':' Type ':=' Expr { Grammatica.Abs.VarDecl $2 $4 $6 }
  | 'def' Ident '(' ListParameter ')' ':' Type SBlock { Grammatica.Abs.FunDecl $2 $4 $7 $8 }

ListParameter :: { [Grammatica.Abs.Parameter] }
ListParameter
  : {- empty -} { [] }
  | Parameter { (:[]) $1 }
  | Parameter ',' ListParameter { (:) $1 $3 }

Parameter :: { Grammatica.Abs.Parameter }
Parameter
  : Modality Ident ':' Type { Grammatica.Abs.Param $1 $2 $4 }

Modality :: { Grammatica.Abs.Modality }
Modality
  : {- empty -} { Grammatica.Abs.Modality1 }
  | 'val' { Grammatica.Abs.Modality_val }
  | 'ref' { Grammatica.Abs.Modality_ref }

Type :: { Grammatica.Abs.Type }
Type
  : SBasicType { Grammatica.Abs.BasicType $1 }
  | '[' Expr ']' Type { Grammatica.Abs.ArrayType $2 $4 }
  | '[' ']' Type { Grammatica.Abs.UnsizedArrayType $3 }
  | '&' Type { Grammatica.Abs.Pointer $2 }

SBasicType :: { Grammatica.Abs.SBasicType }
SBasicType
  : 'bool' { Grammatica.Abs.SBasicType_bool }
  | 'char' { Grammatica.Abs.SBasicType_char }
  | 'int' { Grammatica.Abs.SBasicType_int }
  | 'string' { Grammatica.Abs.SBasicType_string }
  | 'float' { Grammatica.Abs.SBasicType_float }
  | 'void' { Grammatica.Abs.SBasicType_void }

SStatement :: { Grammatica.Abs.SStatement }
SStatement
  : SBlock { Grammatica.Abs.Compound $1 }
  | FunCall { Grammatica.Abs.ProcCall $1 }
  | JumpSStatement { Grammatica.Abs.Jump $1 }
  | IterSStatement { Grammatica.Abs.Iter $1 }
  | BranchSStatement { Grammatica.Abs.Branch $1 }
  | Expr Assignment_op Expr { Grammatica.Abs.Assign $1 $2 $3 }
  | SStatement1 { $1 }

Assignment_op :: { Grammatica.Abs.Assignment_op }
Assignment_op
  : ':=' { Grammatica.Abs.AssignOp }
  | '*=' { Grammatica.Abs.AssignMul }
  | '+=' { Grammatica.Abs.AssignAdd }
  | '/=' { Grammatica.Abs.AssignDiv }
  | '-=' { Grammatica.Abs.AssignSub }
  | '^=' { Grammatica.Abs.AssignPow }
  | '&=' { Grammatica.Abs.AssignAnd }
  | '|=' { Grammatica.Abs.AssignOr }

JumpSStatement :: { Grammatica.Abs.JumpSStatement }
JumpSStatement
  : 'break' { Grammatica.Abs.Break }
  | 'continue' { Grammatica.Abs.Continue }
  | 'return' { Grammatica.Abs.RetExpVoid }
  | 'return' Expr { Grammatica.Abs.RetExp $2 }

BranchSStatement :: { Grammatica.Abs.BranchSStatement }
BranchSStatement
  : 'if' '(' Expr ')' SBlock { Grammatica.Abs.IfNoElse $3 $5 }
  | 'if' '(' Expr ')' SBlock 'else' SBlock { Grammatica.Abs.IfElse $3 $5 $7 }

IterSStatement :: { Grammatica.Abs.IterSStatement }
IterSStatement
  : 'while' '(' Expr ')' SBlock { Grammatica.Abs.While $3 $5 }

Expr :: { Grammatica.Abs.Expr }
Expr : Expr '||' Expr1 { Grammatica.Abs.Or $1 $3 } | Expr1 { $1 }

Expr1 :: { Grammatica.Abs.Expr }
Expr1
  : Expr1 '&&' Expr2 { Grammatica.Abs.And $1 $3 } | Expr2 { $1 }

Expr2 :: { Grammatica.Abs.Expr }
Expr2 : '!' Expr3 { Grammatica.Abs.Not $2 } | Expr3 { $1 }

Expr3 :: { Grammatica.Abs.Expr }
Expr3
  : Expr4 '==' Expr4 { Grammatica.Abs.Eq $1 $3 }
  | Expr4 '!=' Expr4 { Grammatica.Abs.Neq $1 $3 }
  | Expr4 '<' Expr4 { Grammatica.Abs.Lt $1 $3 }
  | Expr4 '<=' Expr4 { Grammatica.Abs.LtE $1 $3 }
  | Expr4 '>' Expr4 { Grammatica.Abs.Gt $1 $3 }
  | Expr4 '>=' Expr4 { Grammatica.Abs.GtE $1 $3 }
  | Expr4 { $1 }

Expr4 :: { Grammatica.Abs.Expr }
Expr4
  : Expr4 '+' Expr5 { Grammatica.Abs.Add $1 $3 }
  | Expr4 '-' Expr5 { Grammatica.Abs.Sub $1 $3 }
  | Expr5 { $1 }

Expr5 :: { Grammatica.Abs.Expr }
Expr5
  : Expr5 '*' Expr6 { Grammatica.Abs.Mul $1 $3 }
  | Expr5 '/' Expr6 { Grammatica.Abs.Div $1 $3 }
  | Expr5 '%' Expr6 { Grammatica.Abs.Mod $1 $3 }
  | Expr6 { $1 }

Expr6 :: { Grammatica.Abs.Expr }
Expr6
  : Expr7 '**' Expr6 { Grammatica.Abs.Pow $1 $3 } | Expr7 { $1 }

Expr7 :: { Grammatica.Abs.Expr }
Expr7 : '-' Expr8 { Grammatica.Abs.Neg $2 } | Expr8 { $1 }

Expr8 :: { Grammatica.Abs.Expr }
Expr8
  : '&' Expr8 { Grammatica.Abs.Ref $2 }
  | '$' Expr8 { Grammatica.Abs.Deref $2 }
  | Expr8 '[' Expr ']' { Grammatica.Abs.ArrayAcc $1 $3 }
  | Expr9 { $1 }

Expr9 :: { Grammatica.Abs.Expr }
Expr9
  : Ident { Grammatica.Abs.Id $1 }
  | SStatement1 { Grammatica.Abs.ExpAssign $1 }
  | Expr10 { $1 }

Expr10 :: { Grammatica.Abs.Expr }
Expr10 : FunCall { Grammatica.Abs.FCall $1 } | Expr11 { $1 }

Expr11 :: { Grammatica.Abs.Expr }
Expr11
  : Integer { Grammatica.Abs.Int $1 }
  | Char { Grammatica.Abs.Char $1 }
  | String { Grammatica.Abs.String $1 }
  | Double { Grammatica.Abs.Float $1 }
  | Boolean { Grammatica.Abs.Bool $1 }
  | Expr12 { $1 }

Boolean :: { Grammatica.Abs.Boolean }
Boolean
  : 'True' { Grammatica.Abs.Boolean_True }
  | 'False' { Grammatica.Abs.Boolean_False }

Expr12 :: { Grammatica.Abs.Expr }
Expr12
  : '[' ListExpr11 ']' { Grammatica.Abs.Array $2 }
  | '(' Expr ')' { $2 }

ListExpr11 :: { [Grammatica.Abs.Expr] }
ListExpr11
  : Expr11 { (:[]) $1 } | Expr11 ',' ListExpr11 { (:) $1 $3 }

SStatement1 :: { Grammatica.Abs.SStatement }
SStatement1
  : '++' Expr8 { Grammatica.Abs.PreInc $2 }
  | '--' Expr8 { Grammatica.Abs.PreDecr $2 }
  | Expr8 '++' { Grammatica.Abs.PostInc $1 }
  | Expr8 '--' { Grammatica.Abs.PostDecr $1 }

FunCall :: { Grammatica.Abs.FunCall }
FunCall : Ident '(' ListExpr ')' { Grammatica.Abs.Call $1 $3 }

ListExpr :: { [Grammatica.Abs.Expr] }
ListExpr
  : {- empty -} { [] }
  | Expr { (:[]) $1 }
  | Expr ',' ListExpr { (:) $1 $3 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

