-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Grammatica.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Grammatica.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Grammatica.Abs.Ident -> Result
transIdent x = case x of
  Grammatica.Abs.Ident string -> failure x

transProgram :: Grammatica.Abs.Program -> Result
transProgram x = case x of
  Grammatica.Abs.Prog decls -> failure x

transDecl :: Grammatica.Abs.Decl -> Result
transDecl x = case x of
  Grammatica.Abs.ConstDecl ident type_ rexpr -> failure x
  Grammatica.Abs.VarDecl ident type_ rexpr -> failure x
  Grammatica.Abs.FunDecl ident parameters type_ block -> failure x

transParameter :: Grammatica.Abs.Parameter -> Result
transParameter x = case x of
  Grammatica.Abs.Param ident type_ -> failure x

transType :: Grammatica.Abs.Type -> Result
transType x = case x of
  Grammatica.Abs.BasType basictype -> failure x
  Grammatica.Abs.CompType compoundtype -> failure x

transBasicType :: Grammatica.Abs.BasicType -> Result
transBasicType x = case x of
  Grammatica.Abs.BasicType_bool -> failure x
  Grammatica.Abs.BasicType_char -> failure x
  Grammatica.Abs.BasicType_int -> failure x
  Grammatica.Abs.BasicType_string -> failure x
  Grammatica.Abs.BasicType_float -> failure x
  Grammatica.Abs.BasicType_void -> failure x

transBoolean :: Grammatica.Abs.Boolean -> Result
transBoolean x = case x of
  Grammatica.Abs.Boolean_True -> failure x
  Grammatica.Abs.Boolean_False -> failure x

transCompoundType :: Grammatica.Abs.CompoundType -> Result
transCompoundType x = case x of
  Grammatica.Abs.ArrDef rexpr type_ -> failure x
  Grammatica.Abs.ArrPartialDef type_ -> failure x
  Grammatica.Abs.Pointer type_ -> failure x

transBlock :: Grammatica.Abs.Block -> Result
transBlock x = case x of
  Grammatica.Abs.BlockDecl decls statements -> failure x

transStatement :: Grammatica.Abs.Statement -> Result
transStatement x = case x of
  Grammatica.Abs.Comp block -> failure x
  Grammatica.Abs.Jmp jumpstatement -> failure x
  Grammatica.Abs.Iter iterstatement -> failure x
  Grammatica.Abs.Sel selectionstatement -> failure x
  Grammatica.Abs.Assgn lexpr assignmentop rexpr -> failure x
  Grammatica.Abs.LExprStatement lexpr -> failure x

transAssignment_op :: Grammatica.Abs.Assignment_op -> Result
transAssignment_op x = case x of
  Grammatica.Abs.Assign -> failure x
  Grammatica.Abs.AssgnMul -> failure x
  Grammatica.Abs.AssgnAdd -> failure x
  Grammatica.Abs.AssgnDiv -> failure x
  Grammatica.Abs.AssgnSub -> failure x
  Grammatica.Abs.AssgnPow -> failure x
  Grammatica.Abs.AssgnAnd -> failure x
  Grammatica.Abs.AssgnOr -> failure x

transJumpStatement :: Grammatica.Abs.JumpStatement -> Result
transJumpStatement x = case x of
  Grammatica.Abs.Break -> failure x
  Grammatica.Abs.Continue -> failure x
  Grammatica.Abs.RetExpVoid -> failure x
  Grammatica.Abs.RetExp rexpr -> failure x

transSelectionStatement :: Grammatica.Abs.SelectionStatement -> Result
transSelectionStatement x = case x of
  Grammatica.Abs.IfNoElse rexpr block -> failure x
  Grammatica.Abs.IfElse rexpr block1 block2 -> failure x

transIterStatement :: Grammatica.Abs.IterStatement -> Result
transIterStatement x = case x of
  Grammatica.Abs.While rexpr block -> failure x

transRExpr :: Grammatica.Abs.RExpr -> Result
transRExpr x = case x of
  Grammatica.Abs.Or rexpr1 rexpr2 -> failure x
  Grammatica.Abs.And rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Not rexpr -> failure x
  Grammatica.Abs.Eq rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Neq rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Lt rexpr1 rexpr2 -> failure x
  Grammatica.Abs.LtE rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Gt rexpr1 rexpr2 -> failure x
  Grammatica.Abs.GtE rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Add rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Sub rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Mul rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Div rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Mod rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Pow rexpr1 rexpr2 -> failure x
  Grammatica.Abs.Neg rexpr -> failure x
  Grammatica.Abs.Ref lexpr -> failure x
  Grammatica.Abs.Int integer -> failure x
  Grammatica.Abs.Char char -> failure x
  Grammatica.Abs.String string -> failure x
  Grammatica.Abs.Float double -> failure x
  Grammatica.Abs.Bool boolean -> failure x
  Grammatica.Abs.Array rexprs -> failure x
  Grammatica.Abs.Lexpr lexpr -> failure x
  Grammatica.Abs.Increment incr -> failure x

transIncr :: Grammatica.Abs.Incr -> Result
transIncr x = case x of
  Grammatica.Abs.PreInc blexpr -> failure x
  Grammatica.Abs.PreDecr blexpr -> failure x
  Grammatica.Abs.PostInc blexpr -> failure x
  Grammatica.Abs.PostDecr blexpr -> failure x

transLExpr :: Grammatica.Abs.LExpr -> Result
transLExpr x = case x of
  Grammatica.Abs.Deref rexpr -> failure x
  Grammatica.Abs.BasLExpr blexpr -> failure x

transBLExpr :: Grammatica.Abs.BLExpr -> Result
transBLExpr x = case x of
  Grammatica.Abs.ArrayEl blexpr rexpr -> failure x
  Grammatica.Abs.Id ident -> failure x
