[project]
name = "driver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["clingo>=5.8.0", "minizinc>=0.10.0", "rich>=14.2.0"]

# [project.scripts]
# driver = "driver:main"

# [build-system]
# requires = ["uv_build>=0.8.5,<0.9.0"]
# build-backend = "uv_build"

# [tool.uv.build-backend]
# module-root = ""
