-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module GrH.Par
  ( happyError
  , myLexer
  , pC
  , pC1
  , pListC2
  , pC2
  , pC4
  , pI
  , pC5
  ) where

import Prelude

import qualified GrH.Abs
import GrH.Lex

}

%name pC C
%name pC1 C1
%name pListC2 ListC2
%name pC2 C2
%name pC4 C4
%name pI I
%name pC5 C5
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('      { PT _ (TS _ 1) }
  ')'      { PT _ (TS _ 2) }
  '*'      { PT _ (TS _ 3) }
  '+'      { PT _ (TS _ 4) }
  L_doubl  { PT _ (TD $$)  }
  L_integ  { PT _ (TI $$)  }

%%

Double  :: { Double }
Double   : L_doubl  { (read $1) :: Double }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

C :: { GrH.Abs.C }
C : C1 { $1 } | C2 { $1 }

C1 :: { GrH.Abs.C }
C1 : C2 '+' ListC2 { GrH.Abs.Chain $1 $3 }

ListC2 :: { [GrH.Abs.C] }
ListC2 : C2 { (:[]) $1 } | C2 '+' ListC2 { (:) $1 $3 }

C2 :: { GrH.Abs.C }
C2 : C5 { $1 } | I '*' C4 { GrH.Abs.Repeat $1 $3 }

C4 :: { GrH.Abs.C }
C4 : C5 { $1 } | C1 { $1 } | '(' C1 ')' { $2 }

I :: { GrH.Abs.I }
I : Integer { GrH.Abs.IntVal $1 }

C5 :: { GrH.Abs.C }
C5 : Double { GrH.Abs.Leaf $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

