-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrH.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrH.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transC :: GrH.Abs.C -> Result
transC x = case x of
  GrH.Abs.Chain c cs -> failure x
  GrH.Abs.Repeat i c -> failure x
  GrH.Abs.Leaf double -> failure x

transI :: GrH.Abs.I -> Result
transI x = case x of
  GrH.Abs.IntVal integer -> failure x
