;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname 1.7.2) (read-case-sensitive #t) (teachpacks ((lib "drawings.ss" "installed-teachpacks"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "drawings.ss" "installed-teachpacks")) #f)))
(define val->btr
  (lambda (num)
    (let ((c (remainder num 3))
          (q (quotient num 3)))
      (if (= num 0)
          ""
          (cond ((= c 0) (string-append (val->btr q) "."))
                ((= c 1) (string-append (val->btr q) "+"))
                ((= c -1) (string-append (val->btr q) "-"))
                ((= c 2) (string-append (val->btr (+ q 1)) "-"))
                ((= c -2) (string-append (val->btr (- q 1)) "+"))
                )))
    ))

(val->btr 0)
(val->btr 1)
(val->btr 2)
(val->btr 3)
(val->btr 4)
(val->btr 5)
(val->btr 6)
(val->btr 7)
(val->btr 8)
(val->btr 9)
(val->btr 10)
(val->btr -0)
(val->btr -1)
(val->btr -2)
(val->btr -3)
(val->btr -4)
(val->btr -5)
(val->btr -6)
(val->btr -7)
(val->btr -8)
(val->btr -9)
(val->btr -10)