-- File generated by the BNF Converter (bnfc 2.9.5).

-- | The abstract syntax of language grA.

module GrA.Abs where

import Prelude (Double, Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data C = Chain [C] | Repeat I C | Leaf Double
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data I = IntVal Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

