-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module GrA.Par
  ( happyError
  , myLexer
  , pC
  , pListC
  , pC1
  , pI
  , pC4
  ) where

import Prelude

import qualified GrA.Abs
import GrA.Lex

}

%name pC C
%name pListC ListC
%name pC1 C1
%name pI I
%name pC4 C4
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('      { PT _ (TS _ 1) }
  ')'      { PT _ (TS _ 2) }
  '*'      { PT _ (TS _ 3) }
  '+'      { PT _ (TS _ 4) }
  L_doubl  { PT _ (TD $$)  }
  L_integ  { PT _ (TI $$)  }

%%

Double  :: { Double }
Double   : L_doubl  { (read $1) :: Double }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

C :: { GrA.Abs.C }
C : ListC { GrA.Abs.Chain $1 }
  | C4 { $1 }
  | I '*' C1 { GrA.Abs.Repeat $1 $3 }

ListC :: { [GrA.Abs.C] }
ListC : C { (:[]) $1 } | C '+' ListC { (:) $1 $3 }

C1 :: { GrA.Abs.C }
C1 : C { $1 } | C4 { $1 }

I :: { GrA.Abs.I }
I : Integer { GrA.Abs.IntVal $1 }

C4 :: { GrA.Abs.C }
C4 : Double { GrA.Abs.Leaf $1 } | '(' C ')' { $2 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

