-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrA.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrA.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transC :: GrA.Abs.C -> Result
transC x = case x of
  GrA.Abs.Chain cs -> failure x
  GrA.Abs.Repeat i c -> failure x
  GrA.Abs.Leaf double -> failure x

transI :: GrA.Abs.I -> Result
transI x = case x of
  GrA.Abs.IntVal integer -> failure x
