-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module GrI.Par
  ( happyError
  , myLexer
  , pE
  , pE1
  , pListE2
  , pE2
  , pE4
  , pE3
  , pI
  ) where

import Prelude

import qualified GrI.Abs
import GrI.Lex

}

%name pE E
%name pE1 E1
%name pListE2 ListE2
%name pE2 E2
%name pE4 E4
%name pE3 E3
%name pI I
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('      { PT _ (TS _ 1) }
  ')'      { PT _ (TS _ 2) }
  '*'      { PT _ (TS _ 3) }
  '+'      { PT _ (TS _ 4) }
  L_doubl  { PT _ (TD $$)  }
  L_integ  { PT _ (TI $$)  }

%%

Double  :: { Double }
Double   : L_doubl  { (read $1) :: Double }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

E :: { GrI.Abs.E }
E : E1 { $1 } | E2 { $1 }

E1 :: { GrI.Abs.E }
E1 : E2 '+' ListE2 { GrI.Abs.Chain $1 $3 }

ListE2 :: { [GrI.Abs.E] }
ListE2 : E2 { (:[]) $1 } | E2 '+' ListE2 { (:) $1 $3 }

E2 :: { GrI.Abs.E }
E2 : E3 { $1 } | I '*' E4 { GrI.Abs.Repeat $1 $3 }

E4 :: { GrI.Abs.E }
E4 : '(' E1 ')' { $2 } | E3 { $1 }

E3 :: { GrI.Abs.E }
E3 : Double { GrI.Abs.Leaf $1 }

I :: { GrI.Abs.I }
I : Integer { GrI.Abs.IntVal $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

