-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrI.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrI.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transE :: GrI.Abs.E -> Result
transE x = case x of
  GrI.Abs.Chain e es -> failure x
  GrI.Abs.Repeat i e -> failure x
  GrI.Abs.Leaf double -> failure x

transI :: GrI.Abs.I -> Result
transI x = case x of
  GrI.Abs.IntVal integer -> failure x
