-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module GrF.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified GrF.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transC :: GrF.Abs.C -> Result
transC x = case x of
  GrF.Abs.Chain cs -> failure x
  GrF.Abs.Repeat i c -> failure x
  GrF.Abs.Leaf double -> failure x

transI :: GrF.Abs.I -> Result
transI x = case x of
  GrF.Abs.IntVal integer -> failure x
